#pragma once
// IWYU pragma private; include "GlobalNamespace/ilReClayUpFdClpKxnBeDJuNJPBMA.hpp"
#include "GlobalNamespace/zzzz__ilReClayUpFdClpKxnBeDJuNJPBMA_def.hpp"
//  Writing Method size for method: ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA.get_keyCategory
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::*)()>(&::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_keyCategory)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(),
                    {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 0}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA.get_scriptingName
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::*)()>(&::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_scriptingName)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(),
                    {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 1}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA.get_nonLocalizedDescriptiveName
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::*)()>(&::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_nonLocalizedDescriptiveName)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(),
                    {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 2}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA.set_nonLocalizedDescriptiveName
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<void (::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::*)(::StringW)>(&::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::set_nonLocalizedDescriptiveName)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(),
                    {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 3}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA.get_key
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::*)()>(&::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_key)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(),
                    {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 4}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA.get_autoGeneratedValueFlags
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<int32_t (::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::*)()>(&::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_autoGeneratedValueFlags)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(),
                    {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 5}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA.set_autoGeneratedValueFlags
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<void (::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::*)(int32_t)>(&::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::set_autoGeneratedValueFlags)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(),
                    {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 6}
                ));
    return ___internal_method;
  }
};
inline ::StringW GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_keyCategory()  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 0}
                        )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline ::StringW GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_scriptingName()  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 1}
                        )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline ::StringW GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_nonLocalizedDescriptiveName()  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 2}
                        )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline void GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::set_nonLocalizedDescriptiveName(::StringW  value)  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 3}
                        )));
return ::cordl_internals::RunMethodRethrow<void>(this, ___internal_method, value);
}
inline ::StringW GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_key()  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 4}
                        )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline int32_t GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::get_autoGeneratedValueFlags()  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 5}
                        )));
return ::cordl_internals::RunMethodRethrow<int32_t>(this, ___internal_method);
}
inline void GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA::set_autoGeneratedValueFlags(int32_t  value)  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*>(), 6}
                        )));
return ::cordl_internals::RunMethodRethrow<void>(this, ___internal_method, value);
}
