#pragma once
// IWYU pragma private; include "GlobalNamespace/SGZfJCNLInnIUumEtCtBXYlOQhsU.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "beatsaber-hook/shared/stringw.hpp"
#include <cstdint>
CORDL_MODULE_EXPORT(SGZfJCNLInnIUumEtCtBXYlOQhsU)
// Forward declare root types
namespace GlobalNamespace {
class SGZfJCNLInnIUumEtCtBXYlOQhsU;
}
// Write type traits
MARK_REF_T(::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*);
DEFINE_IL2CPP_CLASS(::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*, "", "SGZfJCNLInnIUumEtCtBXYlOQhsU");
// Dependencies 
namespace GlobalNamespace {
// Is value type: false
// CS Name: SGZfJCNLInnIUumEtCtBXYlOQhsU
class CORDL_TYPE SGZfJCNLInnIUumEtCtBXYlOQhsU {
public:
// Declarations
 __declspec(property(get=get_autoGeneratedValueFlags, put=set_autoGeneratedValueFlags)) int32_t  autoGeneratedValueFlags;

 __declspec(property(get=get_key)) ::StringW  key;

 __declspec(property(get=get_keyCategory)) ::StringW  keyCategory;

/// @brief Method get_autoGeneratedValueFlags, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline int32_t get_autoGeneratedValueFlags() ;

/// @brief Method get_key, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_key() ;

/// @brief Method get_keyCategory, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_keyCategory() ;

/// @brief Method set_autoGeneratedValueFlags, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline void set_autoGeneratedValueFlags(int32_t  value) ;

// Ctor Parameters [CppParam { name: "", ty: "SGZfJCNLInnIUumEtCtBXYlOQhsU", modifiers: "const&", def_value: None }]
// @brief delete copy ctor to prevent accidental deref copies
SGZfJCNLInnIUumEtCtBXYlOQhsU(SGZfJCNLInnIUumEtCtBXYlOQhsU const& ) = delete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{2863};

static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
} // namespace end def GlobalNamespace
