#pragma once
// IWYU pragma private; include "GlobalNamespace/jJmdHjioTRCYIBJcasPVxXOfznTqA.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "System/zzzz__Object_def.hpp"
#include "beatsaber-hook/shared/stringw.hpp"
#include <cstdint>
CORDL_MODULE_EXPORT(jJmdHjioTRCYIBJcasPVxXOfznTqA)
namespace GlobalNamespace {
class SGZfJCNLInnIUumEtCtBXYlOQhsU;
}
namespace GlobalNamespace {
class tUrLEHAAREMaAAnIKIRxpZlyYYdh;
}
// Forward declare root types
namespace GlobalNamespace {
class jJmdHjioTRCYIBJcasPVxXOfznTqA;
}
// Write type traits
MARK_REF_T(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*);
DEFINE_IL2CPP_CLASS(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*, "", "jJmdHjioTRCYIBJcasPVxXOfznTqA");
// Dependencies System.Object
namespace GlobalNamespace {
// Is value type: false
// CS Name: jJmdHjioTRCYIBJcasPVxXOfznTqA
class CORDL_TYPE jJmdHjioTRCYIBJcasPVxXOfznTqA : public ::System::Object {
public:
// Declarations
 __declspec(property(get=ydyzDNNDpggnAHMMOYQYfcbzoYsQA)) ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  EPzrBiMIUnmexPNEuYQXqCSpWoju;

 __declspec(property(get=Rewired_Internal_Glyphs_IGlyphKeySource_get_autoGeneratedValueFlags, put=Rewired_Internal_Glyphs_IGlyphKeySource_set_autoGeneratedValueFlags)) int32_t  Rewired_Internal_Glyphs_IGlyphKeySource_autoGeneratedValueFlags;

 __declspec(property(get=Rewired_Internal_Glyphs_IGlyphKeySource_get_key)) ::StringW  Rewired_Internal_Glyphs_IGlyphKeySource_key;

 __declspec(property(get=Rewired_Internal_Glyphs_IGlyphKeySource_get_keyCategory)) ::StringW  Rewired_Internal_Glyphs_IGlyphKeySource_keyCategory;

 __declspec(property(get=get_key)) ::StringW  key;

 __declspec(property(get=get_keyCategory)) ::StringW  keyCategory;

/// @brief Field oKTkwfoFIJJNcfeKWmACxkBfjFuF, offset 0x10, size 0x8 
 __declspec(property(get=__cordl_internal_get_oKTkwfoFIJJNcfeKWmACxkBfjFuF, put=__cordl_internal_set_oKTkwfoFIJJNcfeKWmACxkBfjFuF)) ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  oKTkwfoFIJJNcfeKWmACxkBfjFuF;

/// @brief Field rPvUzLZHYmmWlcdZDaDwtvwOvNnO, offset 0x28, size 0x4 
 __declspec(property(get=__cordl_internal_get_rPvUzLZHYmmWlcdZDaDwtvwOvNnO, put=__cordl_internal_set_rPvUzLZHYmmWlcdZDaDwtvwOvNnO)) int32_t  rPvUzLZHYmmWlcdZDaDwtvwOvNnO;

/// @brief Field rSJJdSPgcjTpjLEcVOcAAJtTPJgR, offset 0x20, size 0x8 
 __declspec(property(get=__cordl_internal_get_rSJJdSPgcjTpjLEcVOcAAJtTPJgR, put=__cordl_internal_set_rSJJdSPgcjTpjLEcVOcAAJtTPJgR)) ::StringW  rSJJdSPgcjTpjLEcVOcAAJtTPJgR;

/// @brief Field twbyAkqSfLhCdDeDAgSXdqZSmnCAb, offset 0x18, size 0x8 
 __declspec(property(get=__cordl_internal_get_twbyAkqSfLhCdDeDAgSXdqZSmnCAb, put=__cordl_internal_set_twbyAkqSfLhCdDeDAgSXdqZSmnCAb)) ::StringW  twbyAkqSfLhCdDeDAgSXdqZSmnCAb;

/// @brief Convert operator to "::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU"
constexpr operator  ::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*() noexcept;

/// @brief Method FbQDdPDRSiVfoJjinvJQApPkIrWTA, addr 0x181913410, size 0x80, virtual true, abstract: false, final false
inline bool FbQDdPDRSiVfoJjinvJQApPkIrWTA(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*  _cordl_fixed_empty_name_whitespace) ;

static inline ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA* New_ctor(::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  _cordl_fixed_empty_name_whitespace, ::StringW  _cordl_fixed_empty_name_whitespace_param_1, ::StringW  _cordl_fixed_empty_name_whitespace_param_2) ;

/// @brief Method Rewired.Internal.Glyphs.IGlyphKeySource.get_autoGeneratedValueFlags, addr 0x1803914a0, size 0x10, virtual true, abstract: false, final true
inline int32_t Rewired_Internal_Glyphs_IGlyphKeySource_get_autoGeneratedValueFlags() ;

/// @brief Method Rewired.Internal.Glyphs.IGlyphKeySource.get_key, addr 0x1802d97e0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Glyphs_IGlyphKeySource_get_key() ;

/// @brief Method Rewired.Internal.Glyphs.IGlyphKeySource.get_keyCategory, addr 0x1802ecc10, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Glyphs_IGlyphKeySource_get_keyCategory() ;

/// @brief Method Rewired.Internal.Glyphs.IGlyphKeySource.set_autoGeneratedValueFlags, addr 0x1803914c0, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Glyphs_IGlyphKeySource_set_autoGeneratedValueFlags(int32_t  value) ;

constexpr ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh* const& __cordl_internal_get_oKTkwfoFIJJNcfeKWmACxkBfjFuF() const;

constexpr ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*& __cordl_internal_get_oKTkwfoFIJJNcfeKWmACxkBfjFuF() ;

constexpr int32_t const& __cordl_internal_get_rPvUzLZHYmmWlcdZDaDwtvwOvNnO() const;

constexpr int32_t& __cordl_internal_get_rPvUzLZHYmmWlcdZDaDwtvwOvNnO() ;

constexpr ::StringW const& __cordl_internal_get_rSJJdSPgcjTpjLEcVOcAAJtTPJgR() const;

constexpr ::StringW& __cordl_internal_get_rSJJdSPgcjTpjLEcVOcAAJtTPJgR() ;

constexpr ::StringW const& __cordl_internal_get_twbyAkqSfLhCdDeDAgSXdqZSmnCAb() const;

constexpr ::StringW& __cordl_internal_get_twbyAkqSfLhCdDeDAgSXdqZSmnCAb() ;

constexpr void __cordl_internal_set_oKTkwfoFIJJNcfeKWmACxkBfjFuF(::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  value) ;

constexpr void __cordl_internal_set_rPvUzLZHYmmWlcdZDaDwtvwOvNnO(int32_t  value) ;

constexpr void __cordl_internal_set_rSJJdSPgcjTpjLEcVOcAAJtTPJgR(::StringW  value) ;

constexpr void __cordl_internal_set_twbyAkqSfLhCdDeDAgSXdqZSmnCAb(::StringW  value) ;

/// @brief Method .ctor, addr 0x181913490, size 0x90, virtual false, abstract: false, final false
inline void _ctor(::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  _cordl_fixed_empty_name_whitespace, ::StringW  _cordl_fixed_empty_name_whitespace_param_1, ::StringW  _cordl_fixed_empty_name_whitespace_param_2) ;

/// @brief Method get_key, addr 0x1802d97e0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_key() ;

/// @brief Method get_keyCategory, addr 0x1802ecc10, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_keyCategory() ;

/// @brief Convert to "::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU"
constexpr ::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU* i___GlobalNamespace__SGZfJCNLInnIUumEtCtBXYlOQhsU() noexcept;

/// @brief Method ydyzDNNDpggnAHMMOYQYfcbzoYsQA, addr 0x1802db4a0, size 0x10, virtual false, abstract: false, final false
inline ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh* ydyzDNNDpggnAHMMOYQYfcbzoYsQA() ;

protected:
// Ctor Parameters []
// @brief default ctor
constexpr jJmdHjioTRCYIBJcasPVxXOfznTqA() ;
public:

// Ctor Parameters [CppParam { name: "", ty: "jJmdHjioTRCYIBJcasPVxXOfznTqA", modifiers: "&&", def_value: None }]
// @brief delete move ctor to prevent accidental deref moves
jJmdHjioTRCYIBJcasPVxXOfznTqA(jJmdHjioTRCYIBJcasPVxXOfznTqA && ) = delete;

// Ctor Parameters [CppParam { name: "", ty: "jJmdHjioTRCYIBJcasPVxXOfznTqA", modifiers: "const&", def_value: None }]
// @brief delete copy ctor to prevent accidental deref copies
jJmdHjioTRCYIBJcasPVxXOfznTqA(jJmdHjioTRCYIBJcasPVxXOfznTqA const& ) = delete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{2880};

/// @brief Field oKTkwfoFIJJNcfeKWmACxkBfjFuF, offset: 0x10, size: 0x8, def value: None
 ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  ___oKTkwfoFIJJNcfeKWmACxkBfjFuF;

/// @brief Field twbyAkqSfLhCdDeDAgSXdqZSmnCAb, offset: 0x18, size: 0x8, def value: None
 ::StringW  ___twbyAkqSfLhCdDeDAgSXdqZSmnCAb;

/// @brief Field rSJJdSPgcjTpjLEcVOcAAJtTPJgR, offset: 0x20, size: 0x8, def value: None
 ::StringW  ___rSJJdSPgcjTpjLEcVOcAAJtTPJgR;

/// @brief Field rPvUzLZHYmmWlcdZDaDwtvwOvNnO, offset: 0x28, size: 0x4, def value: None
 int32_t  ___rPvUzLZHYmmWlcdZDaDwtvwOvNnO;

static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
static_assert(offsetof(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA, ___oKTkwfoFIJJNcfeKWmACxkBfjFuF) == 0x10, "Offset mismatch!");

static_assert(offsetof(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA, ___twbyAkqSfLhCdDeDAgSXdqZSmnCAb) == 0x18, "Offset mismatch!");

static_assert(offsetof(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA, ___rSJJdSPgcjTpjLEcVOcAAJtTPJgR) == 0x20, "Offset mismatch!");

static_assert(offsetof(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA, ___rPvUzLZHYmmWlcdZDaDwtvwOvNnO) == 0x28, "Offset mismatch!");

static_assert(sizeof(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA) == 0x30, "Size mismatch!");

} // namespace end def GlobalNamespace
