#pragma once
// IWYU pragma private; include "GlobalNamespace/jJmdHjioTRCYIBJcasPVxXOfznTqA.hpp"
#include "System/zzzz__Object_impl.hpp"
#include "GlobalNamespace/zzzz__jJmdHjioTRCYIBJcasPVxXOfznTqA_def.hpp"
#include "GlobalNamespace/zzzz__SGZfJCNLInnIUumEtCtBXYlOQhsU_def.hpp"
#include "GlobalNamespace/zzzz__tUrLEHAAREMaAAnIKIRxpZlyYYdh_def.hpp"
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA.ydyzDNNDpggnAHMMOYQYfcbzoYsQA
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh* (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)()>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::ydyzDNNDpggnAHMMOYQYfcbzoYsQA)> {
  constexpr static std::size_t size = 0x10;
  constexpr static std::size_t addrs = 0x1802db4a0;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"ydyzDNNDpggnAHMMOYQYfcbzoYsQA", {}, {}}
                    )));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA._ctor
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<void (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)(::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*, ::StringW, ::StringW)>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::_ctor)> {
  constexpr static std::size_t size = 0x90;
  constexpr static std::size_t addrs = 0x181913490;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {".ctor", {}, {::i2c::type_of<::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*>(), ::i2c::type_of<::StringW>(), ::i2c::type_of<::StringW>()}}
                    )));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA.FbQDdPDRSiVfoJjinvJQApPkIrWTA
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<bool (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*)>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::FbQDdPDRSiVfoJjinvJQApPkIrWTA)> {
  constexpr static std::size_t size = 0x80;
  constexpr static std::size_t addrs = 0x181913410;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                    {::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(), 8}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA.Rewired_Internal_Glyphs_IGlyphKeySource_get_keyCategory
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)()>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::Rewired_Internal_Glyphs_IGlyphKeySource_get_keyCategory)> {
  constexpr static std::size_t size = 0x10;
  constexpr static std::size_t addrs = 0x1802ecc10;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"Rewired.Internal.Glyphs.IGlyphKeySource.get_keyCategory", {}, {}}
                    )));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA.Rewired_Internal_Glyphs_IGlyphKeySource_get_key
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)()>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::Rewired_Internal_Glyphs_IGlyphKeySource_get_key)> {
  constexpr static std::size_t size = 0x10;
  constexpr static std::size_t addrs = 0x1802d97e0;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"Rewired.Internal.Glyphs.IGlyphKeySource.get_key", {}, {}}
                    )));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA.Rewired_Internal_Glyphs_IGlyphKeySource_get_autoGeneratedValueFlags
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<int32_t (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)()>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::Rewired_Internal_Glyphs_IGlyphKeySource_get_autoGeneratedValueFlags)> {
  constexpr static std::size_t size = 0x10;
  constexpr static std::size_t addrs = 0x1803914a0;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"Rewired.Internal.Glyphs.IGlyphKeySource.get_autoGeneratedValueFlags", {}, {}}
                    )));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA.Rewired_Internal_Glyphs_IGlyphKeySource_set_autoGeneratedValueFlags
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<void (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)(int32_t)>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::Rewired_Internal_Glyphs_IGlyphKeySource_set_autoGeneratedValueFlags)> {
  constexpr static std::size_t size = 0x10;
  constexpr static std::size_t addrs = 0x1803914c0;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"Rewired.Internal.Glyphs.IGlyphKeySource.set_autoGeneratedValueFlags", {}, {::i2c::type_of<int32_t>()}}
                    )));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA.get_keyCategory
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)()>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::get_keyCategory)> {
  constexpr static std::size_t size = 0x10;
  constexpr static std::size_t addrs = 0x1802ecc10;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"get_keyCategory", {}, {}}
                    )));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA.get_key
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::*)()>(&::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::get_key)> {
  constexpr static std::size_t size = 0x10;
  constexpr static std::size_t addrs = 0x1802d97e0;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"get_key", {}, {}}
                    )));
    return ___internal_method;
  }
};
constexpr ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*& GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_get_oKTkwfoFIJJNcfeKWmACxkBfjFuF()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___oKTkwfoFIJJNcfeKWmACxkBfjFuF;
}
constexpr ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh* const& GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_get_oKTkwfoFIJJNcfeKWmACxkBfjFuF() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___oKTkwfoFIJJNcfeKWmACxkBfjFuF;
}
constexpr void GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_set_oKTkwfoFIJJNcfeKWmACxkBfjFuF(::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___oKTkwfoFIJJNcfeKWmACxkBfjFuF = value;
}
constexpr ::StringW& GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_get_twbyAkqSfLhCdDeDAgSXdqZSmnCAb()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___twbyAkqSfLhCdDeDAgSXdqZSmnCAb;
}
constexpr ::StringW const& GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_get_twbyAkqSfLhCdDeDAgSXdqZSmnCAb() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___twbyAkqSfLhCdDeDAgSXdqZSmnCAb;
}
constexpr void GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_set_twbyAkqSfLhCdDeDAgSXdqZSmnCAb(::StringW  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___twbyAkqSfLhCdDeDAgSXdqZSmnCAb = value;
}
constexpr ::StringW& GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_get_rSJJdSPgcjTpjLEcVOcAAJtTPJgR()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___rSJJdSPgcjTpjLEcVOcAAJtTPJgR;
}
constexpr ::StringW const& GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_get_rSJJdSPgcjTpjLEcVOcAAJtTPJgR() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___rSJJdSPgcjTpjLEcVOcAAJtTPJgR;
}
constexpr void GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_set_rSJJdSPgcjTpjLEcVOcAAJtTPJgR(::StringW  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___rSJJdSPgcjTpjLEcVOcAAJtTPJgR = value;
}
constexpr int32_t& GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_get_rPvUzLZHYmmWlcdZDaDwtvwOvNnO()  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___rPvUzLZHYmmWlcdZDaDwtvwOvNnO;
}
constexpr int32_t const& GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_get_rPvUzLZHYmmWlcdZDaDwtvwOvNnO() const {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
return this->___rPvUzLZHYmmWlcdZDaDwtvwOvNnO;
}
constexpr void GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::__cordl_internal_set_rPvUzLZHYmmWlcdZDaDwtvwOvNnO(int32_t  value)  {
CORDL_FIELD_NULL_CHECK(static_cast<void const*>(this));
this->___rPvUzLZHYmmWlcdZDaDwtvwOvNnO = value;
}
inline ::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh* GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::ydyzDNNDpggnAHMMOYQYfcbzoYsQA()  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"ydyzDNNDpggnAHMMOYQYfcbzoYsQA", {}, {}}
                    )));
return ::cordl_internals::RunMethodRethrow<::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*>(this, ___internal_method);
}
inline void GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::_ctor(::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  _cordl_fixed_empty_name_whitespace, ::StringW  _cordl_fixed_empty_name_whitespace_param_1, ::StringW  _cordl_fixed_empty_name_whitespace_param_2)  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {".ctor", {}, {::i2c::type_of<::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*>(), ::i2c::type_of<::StringW>(), ::i2c::type_of<::StringW>()}}
                    )));
return ::cordl_internals::RunMethodRethrow<void>(this, ___internal_method, _cordl_fixed_empty_name_whitespace, _cordl_fixed_empty_name_whitespace_param_1, _cordl_fixed_empty_name_whitespace_param_2);
}
inline bool GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::FbQDdPDRSiVfoJjinvJQApPkIrWTA(::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*  _cordl_fixed_empty_name_whitespace)  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(), 8}
                        )));
return ::cordl_internals::RunMethodRethrow<bool>(this, ___internal_method, _cordl_fixed_empty_name_whitespace);
}
inline ::StringW GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::Rewired_Internal_Glyphs_IGlyphKeySource_get_keyCategory()  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"Rewired.Internal.Glyphs.IGlyphKeySource.get_keyCategory", {}, {}}
                    )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline ::StringW GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::Rewired_Internal_Glyphs_IGlyphKeySource_get_key()  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"Rewired.Internal.Glyphs.IGlyphKeySource.get_key", {}, {}}
                    )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline int32_t GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::Rewired_Internal_Glyphs_IGlyphKeySource_get_autoGeneratedValueFlags()  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"Rewired.Internal.Glyphs.IGlyphKeySource.get_autoGeneratedValueFlags", {}, {}}
                    )));
return ::cordl_internals::RunMethodRethrow<int32_t>(this, ___internal_method);
}
inline void GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::Rewired_Internal_Glyphs_IGlyphKeySource_set_autoGeneratedValueFlags(int32_t  value)  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"Rewired.Internal.Glyphs.IGlyphKeySource.set_autoGeneratedValueFlags", {}, {::i2c::type_of<int32_t>()}}
                    )));
return ::cordl_internals::RunMethodRethrow<void>(this, ___internal_method, value);
}
inline ::StringW GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::get_keyCategory()  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"get_keyCategory", {}, {}}
                    )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline ::StringW GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::get_key()  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(),
                        {"get_key", {}, {}}
                    )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA* GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::New_ctor(::GlobalNamespace::tUrLEHAAREMaAAnIKIRxpZlyYYdh*  _cordl_fixed_empty_name_whitespace, ::StringW  _cordl_fixed_empty_name_whitespace_param_1, ::StringW  _cordl_fixed_empty_name_whitespace_param_2)  {
return THROW_UNLESS(::i2c::no_logger{}, ::i2c::new_ctor<::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA*>(_cordl_fixed_empty_name_whitespace, _cordl_fixed_empty_name_whitespace_param_1, _cordl_fixed_empty_name_whitespace_param_2));
}
/// @brief Convert operator to "::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU"
constexpr  GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::operator ::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*() noexcept {
return static_cast<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(static_cast<void*>(this));
}
/// @brief Convert to "::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU"
constexpr ::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU* GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::i___GlobalNamespace__SGZfJCNLInnIUumEtCtBXYlOQhsU() noexcept {
return static_cast<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(static_cast<void*>(this));
}
// Ctor Parameters []
constexpr ::GlobalNamespace::jJmdHjioTRCYIBJcasPVxXOfznTqA::jJmdHjioTRCYIBJcasPVxXOfznTqA()   {
}
