#pragma once
// IWYU pragma private; include "GlobalNamespace/SGZfJCNLInnIUumEtCtBXYlOQhsU.hpp"
#include "GlobalNamespace/zzzz__SGZfJCNLInnIUumEtCtBXYlOQhsU_def.hpp"
//  Writing Method size for method: ::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU.get_keyCategory
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::*)()>(&::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::get_keyCategory)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(),
                    {::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(), 0}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU.get_key
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<::StringW (::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::*)()>(&::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::get_key)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(),
                    {::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(), 1}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU.get_autoGeneratedValueFlags
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<int32_t (::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::*)()>(&::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::get_autoGeneratedValueFlags)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(),
                    {::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(), 2}
                ));
    return ___internal_method;
  }
};
//  Writing Method size for method: ::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU.set_autoGeneratedValueFlags
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<void (::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::*)(int32_t)>(&::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::set_autoGeneratedValueFlags)> {
  constexpr static std::size_t size = 0xffffffffffffffff;
  constexpr static std::size_t addrs = 0xffffffffffffffff;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, ::i2c::find_method(
                    ::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(),
                    {::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(), 3}
                ));
    return ___internal_method;
  }
};
inline ::StringW GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::get_keyCategory()  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(), 0}
                        )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline ::StringW GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::get_key()  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(), 1}
                        )));
return ::cordl_internals::RunMethodRethrow<::StringW>(this, ___internal_method);
}
inline int32_t GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::get_autoGeneratedValueFlags()  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(), 2}
                        )));
return ::cordl_internals::RunMethodRethrow<int32_t>(this, ___internal_method);
}
inline void GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU::set_autoGeneratedValueFlags(int32_t  value)  {
auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                            reinterpret_cast<Il2CppObject*>(this)->klass,
                            {::i2c::class_of<::GlobalNamespace::SGZfJCNLInnIUumEtCtBXYlOQhsU*>(), 3}
                        )));
return ::cordl_internals::RunMethodRethrow<void>(this, ___internal_method, value);
}
