#pragma once
// IWYU pragma private; include "Rewired/Interfaces/IControllerElementIdentifierCommon_Internal.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "beatsaber-hook/shared/stringw.hpp"
#include <cstdint>
CORDL_MODULE_EXPORT(IControllerElementIdentifierCommon_Internal)
namespace Rewired::Internal::Localization {
class DeviceLocalizationInfo;
}
namespace Rewired {
struct ControllerElementType;
}
namespace System {
class Object;
}
// Forward declare root types
namespace Rewired::Interfaces {
class IControllerElementIdentifierCommon_Internal;
}
// Write type traits
MARK_REF_T(::Rewired::Interfaces::IControllerElementIdentifierCommon_Internal*);
DEFINE_IL2CPP_CLASS(::Rewired::Interfaces::IControllerElementIdentifierCommon_Internal*, "Rewired.Interfaces", "IControllerElementIdentifierCommon_Internal");
// Dependencies 
namespace Rewired::Interfaces {
// Is value type: false
// CS Name: Rewired.Interfaces.IControllerElementIdentifierCommon_Internal
class CORDL_TYPE IControllerElementIdentifierCommon_Internal {
public:
// Declarations
 __declspec(property(get=get_deviceLocalizationInfo)) ::Rewired::Internal::Localization::DeviceLocalizationInfo*  deviceLocalizationInfo;

 __declspec(property(get=get_editorElementTypeOverride)) ::Rewired::ControllerElementType  editorElementTypeOverride;

 __declspec(property(get=get_elementType)) ::System::Object*  elementType;

 __declspec(property(get=get_id)) int32_t  id;

 __declspec(property(get=get_isNegativeKeyAutoGenerated)) bool  isNegativeKeyAutoGenerated;

 __declspec(property(get=get_isNonLocalizedNegativeNameAutoGenerated)) bool  isNonLocalizedNegativeNameAutoGenerated;

 __declspec(property(get=get_isNonLocalizedPositiveNameAutoGenerated)) bool  isNonLocalizedPositiveNameAutoGenerated;

 __declspec(property(get=get_isPositiveKeyAutoGenerated)) bool  isPositiveKeyAutoGenerated;

 __declspec(property(get=get_key)) ::StringW  key;

 __declspec(property(get=get_name)) ::StringW  name;

 __declspec(property(get=get_negativeKey)) ::StringW  negativeKey;

 __declspec(property(get=get_negativeName)) ::StringW  negativeName;

 __declspec(property(get=get_nonLocalizedName)) ::StringW  nonLocalizedName;

 __declspec(property(get=get_nonLocalizedNegativeName)) ::StringW  nonLocalizedNegativeName;

 __declspec(property(get=get_nonLocalizedPositiveName)) ::StringW  nonLocalizedPositiveName;

 __declspec(property(get=get_positiveKey)) ::StringW  positiveKey;

 __declspec(property(get=get_positiveName)) ::StringW  positiveName;

 __declspec(property(get=get_useEditorElementTypeOverride)) bool  useEditorElementTypeOverride;

/// @brief Method GetSpecialElementKey, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW GetSpecialElementKey(int32_t  index) ;

/// @brief Method GetSpecialElementNonLocalizedName, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW GetSpecialElementNonLocalizedName(int32_t  index) ;

/// @brief Method get_deviceLocalizationInfo, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::Rewired::Internal::Localization::DeviceLocalizationInfo* get_deviceLocalizationInfo() ;

/// @brief Method get_editorElementTypeOverride, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::Rewired::ControllerElementType get_editorElementTypeOverride() ;

/// @brief Method get_elementType, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::System::Object* get_elementType() ;

/// @brief Method get_id, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline int32_t get_id() ;

/// @brief Method get_isNegativeKeyAutoGenerated, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline bool get_isNegativeKeyAutoGenerated() ;

/// @brief Method get_isNonLocalizedNegativeNameAutoGenerated, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline bool get_isNonLocalizedNegativeNameAutoGenerated() ;

/// @brief Method get_isNonLocalizedPositiveNameAutoGenerated, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline bool get_isNonLocalizedPositiveNameAutoGenerated() ;

/// @brief Method get_isPositiveKeyAutoGenerated, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline bool get_isPositiveKeyAutoGenerated() ;

/// @brief Method get_key, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_key() ;

/// @brief Method get_name, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_name() ;

/// @brief Method get_negativeKey, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_negativeKey() ;

/// @brief Method get_negativeName, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_negativeName() ;

/// @brief Method get_nonLocalizedName, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_nonLocalizedName() ;

/// @brief Method get_nonLocalizedNegativeName, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_nonLocalizedNegativeName() ;

/// @brief Method get_nonLocalizedPositiveName, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_nonLocalizedPositiveName() ;

/// @brief Method get_positiveKey, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_positiveKey() ;

/// @brief Method get_positiveName, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_positiveName() ;

/// @brief Method get_useEditorElementTypeOverride, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline bool get_useEditorElementTypeOverride() ;

// Ctor Parameters [CppParam { name: "", ty: "IControllerElementIdentifierCommon_Internal", modifiers: "const&", def_value: None }]
// @brief delete copy ctor to prevent accidental deref copies
IControllerElementIdentifierCommon_Internal(IControllerElementIdentifierCommon_Internal const& ) = delete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{2238};

static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
} // namespace end def Rewired::Interfaces
