#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardDefinitionByIndexOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardDefinitionByIndexOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardDefinitionByLeaderboardIdOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardDefinitionByLeaderboardIdOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardRecordByIndexOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardRecordByIndexOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardRecordByUserIdOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardRecordByUserIdOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardUserScoreByIndexOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardUserScoreByIndexOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardUserScoreByUserIdOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/CopyLeaderboardUserScoreByUserIdOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/Definition.hpp"
#include "Epic/OnlineServices/Leaderboards/DefinitionInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/GetLeaderboardDefinitionCountOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/GetLeaderboardDefinitionCountOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/GetLeaderboardRecordCountOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/GetLeaderboardRecordCountOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/GetLeaderboardUserScoreCountOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/GetLeaderboardUserScoreCountOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/LeaderboardAggregation.hpp"
#include "Epic/OnlineServices/Leaderboards/LeaderboardRecord.hpp"
#include "Epic/OnlineServices/Leaderboards/LeaderboardRecordInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/LeaderboardUserScore.hpp"
#include "Epic/OnlineServices/Leaderboards/LeaderboardUserScoreInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/LeaderboardsInterface.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardDefinitionsCompleteCallback.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardDefinitionsCompleteCallbackInfo.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardDefinitionsCompleteCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardDefinitionsCompleteCallbackInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardDefinitionsCompleteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardRanksCompleteCallback.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardRanksCompleteCallbackInfo.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardRanksCompleteCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardRanksCompleteCallbackInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardRanksCompleteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardUserScoresCompleteCallback.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardUserScoresCompleteCallbackInfo.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardUserScoresCompleteCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardUserScoresCompleteCallbackInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/OnQueryLeaderboardUserScoresCompleteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Leaderboards/QueryLeaderboardDefinitionsOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/QueryLeaderboardDefinitionsOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/QueryLeaderboardRanksOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/QueryLeaderboardRanksOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/QueryLeaderboardUserScoresOptions.hpp"
#include "Epic/OnlineServices/Leaderboards/QueryLeaderboardUserScoresOptionsInternal.hpp"
#include "Epic/OnlineServices/Leaderboards/UserScoresQueryStatInfo.hpp"
#include "Epic/OnlineServices/Leaderboards/UserScoresQueryStatInfoInternal.hpp"
#ifdef __cpp_modules
                    export module Leaderboards;
                    #endif
                
