#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Dissonance/AudioQuality.hpp"
#include "Dissonance/BaseCommsTrigger.hpp"
#include "Dissonance/BaseMicrophoneSubscriber.hpp"
#include "Dissonance/BaseProximityTrigger_1.hpp"
#include "Dissonance/ChannelPriority.hpp"
#include "Dissonance/ChannelProperties.hpp"
#include "Dissonance/ChannelType.hpp"
#include "Dissonance/Channels_2.hpp"
#include "Dissonance/CodecSettings.hpp"
#include "Dissonance/CodecSettingsLoader.hpp"
#include "Dissonance/CommActivationMode.hpp"
#include "Dissonance/CommTriggerTarget.hpp"
#include "Dissonance/DissonanceComms.hpp"
#include "Dissonance/DissonanceException.hpp"
#include "Dissonance/DissonanceRootPath.hpp"
#include "Dissonance/FrameSize.hpp"
#include "Dissonance/FrameSkipDetector.hpp"
#include "Dissonance/IAccessTokenCollection.hpp"
#include "Dissonance/IChannel_1.hpp"
#include "Dissonance/IDissonancePlayer.hpp"
#include "Dissonance/ILossEstimator.hpp"
#include "Dissonance/IRooms.hpp"
#include "Dissonance/IVoiceBroadcastTrigger.hpp"
#include "Dissonance/IVoiceReceiptTrigger.hpp"
#include "Dissonance/LocalVoicePlayerState.hpp"
#include "Dissonance/Log.hpp"
#include "Dissonance/LogCategory.hpp"
#include "Dissonance/LogLevel.hpp"
#include "Dissonance/Logs.hpp"
#include "Dissonance/Metrics.hpp"
#include "Dissonance/NetworkPlayerType.hpp"
#include "Dissonance/PacketLossMonitor.hpp"
#include "Dissonance/PlaybackPool.hpp"
#include "Dissonance/PlayerChannel.hpp"
#include "Dissonance/PlayerChannels.hpp"
#include "Dissonance/PlayerCollection.hpp"
#include "Dissonance/PlayerTrackerManager.hpp"
#include "Dissonance/RemoteChannel.hpp"
#include "Dissonance/RemoteVoicePlayerState.hpp"
#include "Dissonance/RoomChannel.hpp"
#include "Dissonance/RoomChannels.hpp"
#include "Dissonance/RoomIdConversion.hpp"
#include "Dissonance/RoomMembership.hpp"
#include "Dissonance/RoomMembershipComparer.hpp"
#include "Dissonance/RoomName.hpp"
#include "Dissonance/Rooms.hpp"
#include "Dissonance/SemanticVersion.hpp"
#include "Dissonance/TextChat.hpp"
#include "Dissonance/TokenSet.hpp"
#include "Dissonance/Unit.hpp"
#include "Dissonance/VoiceBroadcastTrigger.hpp"
#include "Dissonance/VoicePlayerState.hpp"
#include "Dissonance/VoiceProximityBroadcastTrigger.hpp"
#include "Dissonance/VoiceProximityReceiptTrigger.hpp"
#include "Dissonance/VoiceReceiptTrigger.hpp"
#include "Dissonance/VolumeFaderSettings.hpp"
#ifdef __cpp_modules
                    export module Dissonance;
                    #endif
                
