#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Epic/OnlineServices/Friends/AcceptInviteCallbackInfo.hpp"
#include "Epic/OnlineServices/Friends/AcceptInviteCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/Friends/AcceptInviteOptions.hpp"
#include "Epic/OnlineServices/Friends/AcceptInviteOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/AddNotifyBlockedUsersUpdateOptions.hpp"
#include "Epic/OnlineServices/Friends/AddNotifyBlockedUsersUpdateOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/AddNotifyFriendsUpdateOptions.hpp"
#include "Epic/OnlineServices/Friends/AddNotifyFriendsUpdateOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/FriendsInterface.hpp"
#include "Epic/OnlineServices/Friends/FriendsStatus.hpp"
#include "Epic/OnlineServices/Friends/GetBlockedUserAtIndexOptions.hpp"
#include "Epic/OnlineServices/Friends/GetBlockedUserAtIndexOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/GetBlockedUsersCountOptions.hpp"
#include "Epic/OnlineServices/Friends/GetBlockedUsersCountOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/GetFriendAtIndexOptions.hpp"
#include "Epic/OnlineServices/Friends/GetFriendAtIndexOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/GetFriendsCountOptions.hpp"
#include "Epic/OnlineServices/Friends/GetFriendsCountOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/GetStatusOptions.hpp"
#include "Epic/OnlineServices/Friends/GetStatusOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/OnAcceptInviteCallback.hpp"
#include "Epic/OnlineServices/Friends/OnAcceptInviteCallbackInternal.hpp"
#include "Epic/OnlineServices/Friends/OnAcceptInviteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Friends/OnBlockedUsersUpdateCallback.hpp"
#include "Epic/OnlineServices/Friends/OnBlockedUsersUpdateCallbackInternal.hpp"
#include "Epic/OnlineServices/Friends/OnBlockedUsersUpdateCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Friends/OnBlockedUsersUpdateInfo.hpp"
#include "Epic/OnlineServices/Friends/OnBlockedUsersUpdateInfoInternal.hpp"
#include "Epic/OnlineServices/Friends/OnFriendsUpdateCallback.hpp"
#include "Epic/OnlineServices/Friends/OnFriendsUpdateCallbackInternal.hpp"
#include "Epic/OnlineServices/Friends/OnFriendsUpdateCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Friends/OnFriendsUpdateInfo.hpp"
#include "Epic/OnlineServices/Friends/OnFriendsUpdateInfoInternal.hpp"
#include "Epic/OnlineServices/Friends/OnQueryFriendsCallback.hpp"
#include "Epic/OnlineServices/Friends/OnQueryFriendsCallbackInternal.hpp"
#include "Epic/OnlineServices/Friends/OnQueryFriendsCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Friends/OnRejectInviteCallback.hpp"
#include "Epic/OnlineServices/Friends/OnRejectInviteCallbackInternal.hpp"
#include "Epic/OnlineServices/Friends/OnRejectInviteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Friends/OnSendInviteCallback.hpp"
#include "Epic/OnlineServices/Friends/OnSendInviteCallbackInternal.hpp"
#include "Epic/OnlineServices/Friends/OnSendInviteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/Friends/QueryFriendsCallbackInfo.hpp"
#include "Epic/OnlineServices/Friends/QueryFriendsCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/Friends/QueryFriendsOptions.hpp"
#include "Epic/OnlineServices/Friends/QueryFriendsOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/RejectInviteCallbackInfo.hpp"
#include "Epic/OnlineServices/Friends/RejectInviteCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/Friends/RejectInviteOptions.hpp"
#include "Epic/OnlineServices/Friends/RejectInviteOptionsInternal.hpp"
#include "Epic/OnlineServices/Friends/SendInviteCallbackInfo.hpp"
#include "Epic/OnlineServices/Friends/SendInviteCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/Friends/SendInviteOptions.hpp"
#include "Epic/OnlineServices/Friends/SendInviteOptionsInternal.hpp"
#ifdef __cpp_modules
                    export module Friends;
                    #endif
                
