#pragma once
// IWYU pragma private; include "GlobalNamespace/WBfKBBBVwYdQipIgVVLohIsYgBpdA.hpp"
#include "System/zzzz__IntPtr_impl.hpp"
#include "System/zzzz__Object_impl.hpp"
#include "GlobalNamespace/zzzz__WBfKBBBVwYdQipIgVVLohIsYgBpdA_def.hpp"
#include "GlobalNamespace/zzzz__WBfKBBBVwYdQipIgVVLohIsYgBpdA_def.hpp"
// Ctor Parameters []
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_YGBvKQChmwQnZHxUzSpCWyXRSgcS::WBfKBBBVwYdQipIgVVLohIsYgBpdA_YGBvKQChmwQnZHxUzSpCWyXRSgcS()   {
}
// Ctor Parameters [CppParam { name: "value__", ty: "int32_t", modifiers: "", def_value: Some("{}") }]
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye(int32_t  value__) noexcept  {
this->value__ = value__;
}
// Ctor Parameters []
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye()   {
}
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Albanian{static_cast<int32_t>(0x41c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Arabic_101{static_cast<int32_t>(0x401)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Arabic_102{static_cast<int32_t>(0x10401)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Arabic_102_AZERTY{static_cast<int32_t>(0x20401)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Armenian_Eastern{static_cast<int32_t>(0x42b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Armenian_Phonetic{static_cast<int32_t>(0x2042b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Armenian_Typewriter{static_cast<int32_t>(0x3042b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Armenian_Western{static_cast<int32_t>(0x1042b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Assamese_Inscript{static_cast<int32_t>(0x44d)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Azerbaijani_Standard{static_cast<int32_t>(0x1042c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Azerbaijani_Cyrillic{static_cast<int32_t>(0x82c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Azerbaijani_Latin{static_cast<int32_t>(0x42c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bashkir{static_cast<int32_t>(0x46d)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Belarusian{static_cast<int32_t>(0x423)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Belgian_Comma{static_cast<int32_t>(0x1080c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Belgian_Period{static_cast<int32_t>(0x813)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Belgian_French{static_cast<int32_t>(0x80c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bangla_Bangladesh{static_cast<int32_t>(0x445)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bangla_India{static_cast<int32_t>(0x20445)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bangla_India_Legacy{static_cast<int32_t>(0x10445)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bosnian_Cyrillic{static_cast<int32_t>(0x201a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Buginese{static_cast<int32_t>(0xb0c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bulgarian{static_cast<int32_t>(0x30402)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bulgarian_Latin{static_cast<int32_t>(0x10402)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bulgarian_phonetic_layout{static_cast<int32_t>(0x20402)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bulgarian_phonetic_traditional{static_cast<int32_t>(0x40402)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Bulgarian_Typewriter{static_cast<int32_t>(0x402)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Canadian_French{static_cast<int32_t>(0x1009)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Canadian_French_Legacy{static_cast<int32_t>(0xc0c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Canadian_Multilingual_Standard{static_cast<int32_t>(0x11009)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Central_Atlas_Tamazight{static_cast<int32_t>(0x85f)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Central_Kurdish{static_cast<int32_t>(0x429)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Cherokee_Nation{static_cast<int32_t>(0x45c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Cherokee_Nation_Phonetic{static_cast<int32_t>(0x1045c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Chinese_Simplified_US_Keyboard{static_cast<int32_t>(0x804)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Chinese_Traditional_US_Keyboard{static_cast<int32_t>(0x404)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Chinese_Traditional{static_cast<int32_t>(0x405)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::_Hong_Kong_S_A_R_{static_cast<int32_t>(0xc04)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Chinese_Traditional_Macao_S_A_R__US_Keyboard{static_cast<int32_t>(0x1404)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Chinese_Simplified{static_cast<int32_t>(0x1405)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::_Singapore_US_keyboard{static_cast<int32_t>(0x1004)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Croatian{static_cast<int32_t>(0x41a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Czech{static_cast<int32_t>(0x405)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Czech_QWERTY{static_cast<int32_t>(0x10405)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Czech_Programmers{static_cast<int32_t>(0x20405)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Danish{static_cast<int32_t>(0x406)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::DevanagariINSCRIPT{static_cast<int32_t>(0x439)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Divehi_Phonetic{static_cast<int32_t>(0x465)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Divehi_Typewriter{static_cast<int32_t>(0x10465)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Dutch{static_cast<int32_t>(0x413)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Dzongkha{static_cast<int32_t>(0xc51)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Estonian{static_cast<int32_t>(0x425)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Faeroese{static_cast<int32_t>(0x438)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Finnish{static_cast<int32_t>(0x40b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Finnish_with_Sami{static_cast<int32_t>(0x1083b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::French{static_cast<int32_t>(0x40c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Futhark{static_cast<int32_t>(0x120c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Georgian{static_cast<int32_t>(0x437)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Georgian_Ergonomic{static_cast<int32_t>(0x20437)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Georgian_QWERTY{static_cast<int32_t>(0x10437)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Georgian_Ministry_of_Education_and_Science_Schools{static_cast<int32_t>(0x30437)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Georgian_Old_Alphabets{static_cast<int32_t>(0x40437)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::German{static_cast<int32_t>(0x407)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::German_IBM{static_cast<int32_t>(0x10407)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Gothic{static_cast<int32_t>(0xc0c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Greek{static_cast<int32_t>(0x408)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Greek_220{static_cast<int32_t>(0x10408)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Greek_220_Latin{static_cast<int32_t>(0x30408)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Greek_319{static_cast<int32_t>(0x20408)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Greek_319_Latin{static_cast<int32_t>(0x40408)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Greek_Latin{static_cast<int32_t>(0x50408)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Greek_Polytonic{static_cast<int32_t>(0x60408)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Greenlandic{static_cast<int32_t>(0x46f)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Guarani{static_cast<int32_t>(0x474)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Gujarati{static_cast<int32_t>(0x447)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Hausa{static_cast<int32_t>(0x468)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Hebrew{static_cast<int32_t>(0x40d)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Hindi_Traditional{static_cast<int32_t>(0x10439)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Hungarian{static_cast<int32_t>(0x40e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Hungarian_101key{static_cast<int32_t>(0x1040e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Icelandic{static_cast<int32_t>(0x40f)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Igbo{static_cast<int32_t>(0x470)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::India{static_cast<int32_t>(0x4009)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Inuktitut_Latin{static_cast<int32_t>(0x85d)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Inuktitut_Naqittaut{static_cast<int32_t>(0x1045d)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Irish{static_cast<int32_t>(0x1809)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Italian{static_cast<int32_t>(0x410)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Italian_142{static_cast<int32_t>(0x10410)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Japanese{static_cast<int32_t>(0x411)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Javanese{static_cast<int32_t>(0x110c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Kannada{static_cast<int32_t>(0x44b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Kazakh{static_cast<int32_t>(0x43f)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Khmer{static_cast<int32_t>(0x453)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Khmer_NIDA{static_cast<int32_t>(0x10453)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Korean{static_cast<int32_t>(0x412)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Kyrgyz_Cyrillic{static_cast<int32_t>(0x440)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Lao{static_cast<int32_t>(0x454)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Latin_American{static_cast<int32_t>(0x80a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Latvian_Standard{static_cast<int32_t>(0x20426)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Latvian_Legacy{static_cast<int32_t>(0x10426)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Lisu_Basic{static_cast<int32_t>(0x70c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Lisu_Standard{static_cast<int32_t>(0x80c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Lithuanian{static_cast<int32_t>(0x10427)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Lithuanian_IBM{static_cast<int32_t>(0x427)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Lithuanian_Standard{static_cast<int32_t>(0x20427)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Luxembourgish{static_cast<int32_t>(0x46e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Macedonia_FYROM{static_cast<int32_t>(0x42f)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Macedonia_FYROM_Standard{static_cast<int32_t>(0x1042f)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Malayalam{static_cast<int32_t>(0x44c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Maltese_47Key{static_cast<int32_t>(0x43a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Maltese_48key{static_cast<int32_t>(0x1043a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Maori{static_cast<int32_t>(0x481)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Marathi{static_cast<int32_t>(0x44e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Mongolian_Mongolian_Script_Legacy{static_cast<int32_t>(0x850)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Mongolian_Mongolian_Script_Standard{static_cast<int32_t>(0x20850)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Mongolian_Cyrillic{static_cast<int32_t>(0x450)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Myanmar{static_cast<int32_t>(0x10c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::N_ko{static_cast<int32_t>(0x90c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Nepali{static_cast<int32_t>(0x461)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::New_Tai_Lue{static_cast<int32_t>(0x20c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Norwegian{static_cast<int32_t>(0x414)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Norwegian_with_Sami{static_cast<int32_t>(0x43b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Odia{static_cast<int32_t>(0x448)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Ol_Chiki{static_cast<int32_t>(0xd0c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Old_Italic{static_cast<int32_t>(0xf0c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Osmanya{static_cast<int32_t>(0xe0c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Pashto_Afghanistan{static_cast<int32_t>(0x463)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Persian{static_cast<int32_t>(0x429)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Persian_Standard{static_cast<int32_t>(0x50429)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Phagspa{static_cast<int32_t>(0xa0c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Polish_214{static_cast<int32_t>(0x10415)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Polish_Programmers{static_cast<int32_t>(0x415)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Portuguese{static_cast<int32_t>(0x816)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Portuguese_Brazilian_ABNT{static_cast<int32_t>(0x416)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Portuguese_Brazilian_ABNT2{static_cast<int32_t>(0x10416)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Punjabi{static_cast<int32_t>(0x446)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Romanian_Legacy{static_cast<int32_t>(0x418)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Romanian_Programmers{static_cast<int32_t>(0x20418)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Romanian_Standard{static_cast<int32_t>(0x10418)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Russian{static_cast<int32_t>(0x419)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Russian_Mnemonic{static_cast<int32_t>(0x20419)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Russian_Typewriter{static_cast<int32_t>(0x10419)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sakha{static_cast<int32_t>(0x485)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sami_Extended_FinlandSweden{static_cast<int32_t>(0x2083b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sami_Extended_Norway{static_cast<int32_t>(0x1043b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Scottish_Gaelic{static_cast<int32_t>(0x11809)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Serbian_Cyrillic{static_cast<int32_t>(0xc1a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Serbian_Latin{static_cast<int32_t>(0x81a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sesotho_sa_Leboa{static_cast<int32_t>(0x46c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Setswana{static_cast<int32_t>(0x432)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sinhala{static_cast<int32_t>(0x45b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sinhala_wij_9{static_cast<int32_t>(0x1045b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Slovak{static_cast<int32_t>(0x41b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Slovak_QWERTY{static_cast<int32_t>(0x1041b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Slovenian{static_cast<int32_t>(0x424)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sora{static_cast<int32_t>(0x100c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sorbian_Extended{static_cast<int32_t>(0x1042e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sorbian_Standard{static_cast<int32_t>(0x2042e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Sorbian_Standard_Legacy{static_cast<int32_t>(0x42e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Spanish{static_cast<int32_t>(0x40a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Spanish_Variation{static_cast<int32_t>(0x1040a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Swedish{static_cast<int32_t>(0x41d)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Swedish_with_Sami{static_cast<int32_t>(0x83b)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Swiss_French{static_cast<int32_t>(0x100c)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Swiss_German{static_cast<int32_t>(0x807)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Syriac{static_cast<int32_t>(0x45a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Syriac_Phonetic{static_cast<int32_t>(0x1045a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tai_Le{static_cast<int32_t>(0x30c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tajik{static_cast<int32_t>(0x428)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tamil{static_cast<int32_t>(0x449)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tatar{static_cast<int32_t>(0x10444)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tatar_Legacy{static_cast<int32_t>(0x444)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Telugu{static_cast<int32_t>(0x44a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Thai_Kedmanee{static_cast<int32_t>(0x41e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Thai_Kedmanee_nonShiftLock{static_cast<int32_t>(0x2041e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Thai_Pattachote{static_cast<int32_t>(0x1041e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Thai_Pattachote_nonShiftLock{static_cast<int32_t>(0x3041e)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tibetan_PRC_Standard{static_cast<int32_t>(0x10451)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tibetan_PRC_Legacy{static_cast<int32_t>(0x451)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tifinagh_Basic{static_cast<int32_t>(0x50c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Tifinagh_Full{static_cast<int32_t>(0x60c00)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Turkish_F{static_cast<int32_t>(0x1041f)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Turkish_Q{static_cast<int32_t>(0x41f)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Turkmen{static_cast<int32_t>(0x442)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Ukrainian{static_cast<int32_t>(0x422)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Ukrainian_Enhanced{static_cast<int32_t>(0x20422)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::United_Kingdom{static_cast<int32_t>(0x809)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::United_Kingdom_Extended{static_cast<int32_t>(0x452)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::United_States_Dvorak{static_cast<int32_t>(0x10409)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::United_States_International{static_cast<int32_t>(0x20409)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::United_StatesDvorak_for_left_hand{static_cast<int32_t>(0x30409)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::United_StatesDvorak_for_right_hand{static_cast<int32_t>(0x40409)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::United_States_English{static_cast<int32_t>(0x409)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Urdu{static_cast<int32_t>(0x420)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Uyghur{static_cast<int32_t>(0x10480)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Uyghur_Legacy{static_cast<int32_t>(0x480)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Uzbek_Cyrillic{static_cast<int32_t>(0x843)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Vietnamese{static_cast<int32_t>(0x42a)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Wolof{static_cast<int32_t>(0x488)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Yakut{static_cast<int32_t>(0x485)};
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye  GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA_MuuxEMrqxETSNBhMxAaFMeSZZSye::Yoruba{static_cast<int32_t>(0x46a)};
//  Writing Method size for method: ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA._ctor
template<>

struct CORDL_HIDDEN ::i2c::metadata_getter<static_cast<void (::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::*)()>(&::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::_ctor)> {
  constexpr static std::size_t size = 0x10;
  constexpr static std::size_t addrs = 0x1802d9d80;

  inline static const ::MethodInfo* method_info() {
    static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(),
                        {".ctor", {}, {}}
                    )));
    return ___internal_method;
  }
};
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_MlaqjvOdAvsfuUzCBJGrScwxmtXE(::System::IntPtr  value)  {
::cordl_internals::setStaticField<::System::IntPtr, "MlaqjvOdAvsfuUzCBJGrScwxmtXE", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<::System::IntPtr>(value));
}
inline ::System::IntPtr GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_MlaqjvOdAvsfuUzCBJGrScwxmtXE()  {
return ::cordl_internals::getStaticField<::System::IntPtr, "MlaqjvOdAvsfuUzCBJGrScwxmtXE", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_ObmFQceENvRwVaYhAdlqUcCjpQjaA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "ObmFQceENvRwVaYhAdlqUcCjpQjaA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_ObmFQceENvRwVaYhAdlqUcCjpQjaA()  {
return ::cordl_internals::getStaticField<int32_t, "ObmFQceENvRwVaYhAdlqUcCjpQjaA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_WsdTKDptiyePbuJrCFeEzycrwPAG(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "WsdTKDptiyePbuJrCFeEzycrwPAG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_WsdTKDptiyePbuJrCFeEzycrwPAG()  {
return ::cordl_internals::getStaticField<int32_t, "WsdTKDptiyePbuJrCFeEzycrwPAG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_tPPBohVjGQOHQDIbxlqitvyMGNqx(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "tPPBohVjGQOHQDIbxlqitvyMGNqx", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_tPPBohVjGQOHQDIbxlqitvyMGNqx()  {
return ::cordl_internals::getStaticField<int32_t, "tPPBohVjGQOHQDIbxlqitvyMGNqx", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_XYjqGSHLLucideDYsqIoNjtiWzAK(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "XYjqGSHLLucideDYsqIoNjtiWzAK", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_XYjqGSHLLucideDYsqIoNjtiWzAK()  {
return ::cordl_internals::getStaticField<int32_t, "XYjqGSHLLucideDYsqIoNjtiWzAK", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_vfngJNELTlJkdPAFwplgBPAkaOCY(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "vfngJNELTlJkdPAFwplgBPAkaOCY", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_vfngJNELTlJkdPAFwplgBPAkaOCY()  {
return ::cordl_internals::getStaticField<int32_t, "vfngJNELTlJkdPAFwplgBPAkaOCY", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_hhBEoGmSTIrItdphUtVUAOrXiFkD(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "hhBEoGmSTIrItdphUtVUAOrXiFkD", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_hhBEoGmSTIrItdphUtVUAOrXiFkD()  {
return ::cordl_internals::getStaticField<int32_t, "hhBEoGmSTIrItdphUtVUAOrXiFkD", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_UWTNLeofCiOiKaiBlAvvHDKKMXiab(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "UWTNLeofCiOiKaiBlAvvHDKKMXiab", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_UWTNLeofCiOiKaiBlAvvHDKKMXiab()  {
return ::cordl_internals::getStaticField<int32_t, "UWTNLeofCiOiKaiBlAvvHDKKMXiab", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_aWkyeHgSaJGUkRXedCERDRSPUiBH(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "aWkyeHgSaJGUkRXedCERDRSPUiBH", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_aWkyeHgSaJGUkRXedCERDRSPUiBH()  {
return ::cordl_internals::getStaticField<int32_t, "aWkyeHgSaJGUkRXedCERDRSPUiBH", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_SvAWlAABoFjbwnFZBWMjFpJNyaWG(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "SvAWlAABoFjbwnFZBWMjFpJNyaWG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_SvAWlAABoFjbwnFZBWMjFpJNyaWG()  {
return ::cordl_internals::getStaticField<int32_t, "SvAWlAABoFjbwnFZBWMjFpJNyaWG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_nqHulROdAobKUjSbobRtaEoXDOwSA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "nqHulROdAobKUjSbobRtaEoXDOwSA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_nqHulROdAobKUjSbobRtaEoXDOwSA()  {
return ::cordl_internals::getStaticField<int32_t, "nqHulROdAobKUjSbobRtaEoXDOwSA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_gXEerpVJBhtEsJbgpyPgxyBlDKAe(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "gXEerpVJBhtEsJbgpyPgxyBlDKAe", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_gXEerpVJBhtEsJbgpyPgxyBlDKAe()  {
return ::cordl_internals::getStaticField<int32_t, "gXEerpVJBhtEsJbgpyPgxyBlDKAe", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_XXMzhjuQTAavUUWwfxwtyYjlQZFG(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "XXMzhjuQTAavUUWwfxwtyYjlQZFG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_XXMzhjuQTAavUUWwfxwtyYjlQZFG()  {
return ::cordl_internals::getStaticField<int32_t, "XXMzhjuQTAavUUWwfxwtyYjlQZFG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_PbmGEeBSjdLfaxXZSlxcsazHvEwq(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "PbmGEeBSjdLfaxXZSlxcsazHvEwq", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_PbmGEeBSjdLfaxXZSlxcsazHvEwq()  {
return ::cordl_internals::getStaticField<int32_t, "PbmGEeBSjdLfaxXZSlxcsazHvEwq", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_wAbAZItMEByPlarOZltmncGLOXEs(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "wAbAZItMEByPlarOZltmncGLOXEs", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_wAbAZItMEByPlarOZltmncGLOXEs()  {
return ::cordl_internals::getStaticField<int32_t, "wAbAZItMEByPlarOZltmncGLOXEs", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_RTxxxZJSgyaPhLKLewgFFYyVfNUn(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "RTxxxZJSgyaPhLKLewgFFYyVfNUn", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_RTxxxZJSgyaPhLKLewgFFYyVfNUn()  {
return ::cordl_internals::getStaticField<int32_t, "RTxxxZJSgyaPhLKLewgFFYyVfNUn", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_OBjcVdYdCERVbBlzTdMMmQtkPUVQ(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "OBjcVdYdCERVbBlzTdMMmQtkPUVQ", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_OBjcVdYdCERVbBlzTdMMmQtkPUVQ()  {
return ::cordl_internals::getStaticField<int32_t, "OBjcVdYdCERVbBlzTdMMmQtkPUVQ", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_MYMnitclNPFIFmChVcUbQKAyvkRW(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "MYMnitclNPFIFmChVcUbQKAyvkRW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_MYMnitclNPFIFmChVcUbQKAyvkRW()  {
return ::cordl_internals::getStaticField<int32_t, "MYMnitclNPFIFmChVcUbQKAyvkRW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_oySrmxJWuIrYwVzonPbxXBJmBiXQ(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "oySrmxJWuIrYwVzonPbxXBJmBiXQ", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_oySrmxJWuIrYwVzonPbxXBJmBiXQ()  {
return ::cordl_internals::getStaticField<int32_t, "oySrmxJWuIrYwVzonPbxXBJmBiXQ", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_FxoYvECHLoUYjySSOkXVvmuEoBeW(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "FxoYvECHLoUYjySSOkXVvmuEoBeW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_FxoYvECHLoUYjySSOkXVvmuEoBeW()  {
return ::cordl_internals::getStaticField<int32_t, "FxoYvECHLoUYjySSOkXVvmuEoBeW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_beBBNUffFySdMPiIMmPksWhYKvHr(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "beBBNUffFySdMPiIMmPksWhYKvHr", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_beBBNUffFySdMPiIMmPksWhYKvHr()  {
return ::cordl_internals::getStaticField<int32_t, "beBBNUffFySdMPiIMmPksWhYKvHr", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_YgSQhwOTsklRpvHgoZjjcKlExFEn(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "YgSQhwOTsklRpvHgoZjjcKlExFEn", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_YgSQhwOTsklRpvHgoZjjcKlExFEn()  {
return ::cordl_internals::getStaticField<int32_t, "YgSQhwOTsklRpvHgoZjjcKlExFEn", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_IPmTUZHqTdsRYjCrUFBwBdKvZQCW(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "IPmTUZHqTdsRYjCrUFBwBdKvZQCW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_IPmTUZHqTdsRYjCrUFBwBdKvZQCW()  {
return ::cordl_internals::getStaticField<int32_t, "IPmTUZHqTdsRYjCrUFBwBdKvZQCW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_vYSpLQZxkulNowrJIbfUZRccAJss(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "vYSpLQZxkulNowrJIbfUZRccAJss", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_vYSpLQZxkulNowrJIbfUZRccAJss()  {
return ::cordl_internals::getStaticField<int32_t, "vYSpLQZxkulNowrJIbfUZRccAJss", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_dzwyFtcxBKoMTfWFcJvbjNEgxXju(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "dzwyFtcxBKoMTfWFcJvbjNEgxXju", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_dzwyFtcxBKoMTfWFcJvbjNEgxXju()  {
return ::cordl_internals::getStaticField<int32_t, "dzwyFtcxBKoMTfWFcJvbjNEgxXju", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_PhbiaerrcuhZJagJMnoBztPoECWPA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "PhbiaerrcuhZJagJMnoBztPoECWPA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_PhbiaerrcuhZJagJMnoBztPoECWPA()  {
return ::cordl_internals::getStaticField<int32_t, "PhbiaerrcuhZJagJMnoBztPoECWPA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_HAuTBldkthogfRPzyBzemeikgwPg(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "HAuTBldkthogfRPzyBzemeikgwPg", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_HAuTBldkthogfRPzyBzemeikgwPg()  {
return ::cordl_internals::getStaticField<int32_t, "HAuTBldkthogfRPzyBzemeikgwPg", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_ZWedpugWCmqjfQqVrGtFaaNUxZo(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "ZWedpugWCmqjfQqVrGtFaaNUxZo", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_ZWedpugWCmqjfQqVrGtFaaNUxZo()  {
return ::cordl_internals::getStaticField<int32_t, "ZWedpugWCmqjfQqVrGtFaaNUxZo", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_XlbadiAaqgXyZuvFYfMYGqDgAnobb(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "XlbadiAaqgXyZuvFYfMYGqDgAnobb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_XlbadiAaqgXyZuvFYfMYGqDgAnobb()  {
return ::cordl_internals::getStaticField<int32_t, "XlbadiAaqgXyZuvFYfMYGqDgAnobb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_RIccAhitjgDMuBKEcbMujUnxzIWEA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "RIccAhitjgDMuBKEcbMujUnxzIWEA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_RIccAhitjgDMuBKEcbMujUnxzIWEA()  {
return ::cordl_internals::getStaticField<int32_t, "RIccAhitjgDMuBKEcbMujUnxzIWEA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_zEZikoNLfyCGGePqBCMYqIKPiyWCb(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "zEZikoNLfyCGGePqBCMYqIKPiyWCb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_zEZikoNLfyCGGePqBCMYqIKPiyWCb()  {
return ::cordl_internals::getStaticField<int32_t, "zEZikoNLfyCGGePqBCMYqIKPiyWCb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_hvgGcpQJPbdVCAcJYxpJqorshFCoA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "hvgGcpQJPbdVCAcJYxpJqorshFCoA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_hvgGcpQJPbdVCAcJYxpJqorshFCoA()  {
return ::cordl_internals::getStaticField<int32_t, "hvgGcpQJPbdVCAcJYxpJqorshFCoA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_RXajNbxbCgFsjkmblPfOxVXnIKPaA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "RXajNbxbCgFsjkmblPfOxVXnIKPaA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_RXajNbxbCgFsjkmblPfOxVXnIKPaA()  {
return ::cordl_internals::getStaticField<int32_t, "RXajNbxbCgFsjkmblPfOxVXnIKPaA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_pMoLNAgZjhbCJPZpFGjlGgJBhGMdA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "pMoLNAgZjhbCJPZpFGjlGgJBhGMdA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_pMoLNAgZjhbCJPZpFGjlGgJBhGMdA()  {
return ::cordl_internals::getStaticField<int32_t, "pMoLNAgZjhbCJPZpFGjlGgJBhGMdA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_QYgDoTJIhJeoONzfeSlvFlKayJZE(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "QYgDoTJIhJeoONzfeSlvFlKayJZE", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_QYgDoTJIhJeoONzfeSlvFlKayJZE()  {
return ::cordl_internals::getStaticField<int32_t, "QYgDoTJIhJeoONzfeSlvFlKayJZE", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_zugmbdFwdSCfxIvWfFMcKNjkuXAd(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "zugmbdFwdSCfxIvWfFMcKNjkuXAd", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_zugmbdFwdSCfxIvWfFMcKNjkuXAd()  {
return ::cordl_internals::getStaticField<int32_t, "zugmbdFwdSCfxIvWfFMcKNjkuXAd", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_oaTgKnQutSDtJiZCwdQeoKMgquVL(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "oaTgKnQutSDtJiZCwdQeoKMgquVL", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_oaTgKnQutSDtJiZCwdQeoKMgquVL()  {
return ::cordl_internals::getStaticField<int32_t, "oaTgKnQutSDtJiZCwdQeoKMgquVL", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_gdPXqotBuSHTnzjbsEFpbPfXqNgM(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "gdPXqotBuSHTnzjbsEFpbPfXqNgM", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_gdPXqotBuSHTnzjbsEFpbPfXqNgM()  {
return ::cordl_internals::getStaticField<int32_t, "gdPXqotBuSHTnzjbsEFpbPfXqNgM", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_AwidnoZfYmdhWbgtddVaEfxhnMIFb(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "AwidnoZfYmdhWbgtddVaEfxhnMIFb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_AwidnoZfYmdhWbgtddVaEfxhnMIFb()  {
return ::cordl_internals::getStaticField<int32_t, "AwidnoZfYmdhWbgtddVaEfxhnMIFb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_WnqsALewHvJSPDQBTtzUTYSYlpUE(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "WnqsALewHvJSPDQBTtzUTYSYlpUE", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_WnqsALewHvJSPDQBTtzUTYSYlpUE()  {
return ::cordl_internals::getStaticField<int32_t, "WnqsALewHvJSPDQBTtzUTYSYlpUE", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_qoZCxVLfFCwEUegMzDbDxXgDhrMAA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "qoZCxVLfFCwEUegMzDbDxXgDhrMAA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_qoZCxVLfFCwEUegMzDbDxXgDhrMAA()  {
return ::cordl_internals::getStaticField<int32_t, "qoZCxVLfFCwEUegMzDbDxXgDhrMAA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_dIYRsWOVRcXnWONAuTxtNGrGvysD(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "dIYRsWOVRcXnWONAuTxtNGrGvysD", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_dIYRsWOVRcXnWONAuTxtNGrGvysD()  {
return ::cordl_internals::getStaticField<int32_t, "dIYRsWOVRcXnWONAuTxtNGrGvysD", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_eoSBMqXcbwQPctDnaLkUtJFSEwDBA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "eoSBMqXcbwQPctDnaLkUtJFSEwDBA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_eoSBMqXcbwQPctDnaLkUtJFSEwDBA()  {
return ::cordl_internals::getStaticField<int32_t, "eoSBMqXcbwQPctDnaLkUtJFSEwDBA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_WyhxLrcgwbbCMalTRqmFrOoOjKJTA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "WyhxLrcgwbbCMalTRqmFrOoOjKJTA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_WyhxLrcgwbbCMalTRqmFrOoOjKJTA()  {
return ::cordl_internals::getStaticField<int32_t, "WyhxLrcgwbbCMalTRqmFrOoOjKJTA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_NYDblOIbQvlnizguARQXlOkNMDtuA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "NYDblOIbQvlnizguARQXlOkNMDtuA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_NYDblOIbQvlnizguARQXlOkNMDtuA()  {
return ::cordl_internals::getStaticField<int32_t, "NYDblOIbQvlnizguARQXlOkNMDtuA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_ZPbitXgDCyStqgKzIEviyBQsWIdU(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "ZPbitXgDCyStqgKzIEviyBQsWIdU", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_ZPbitXgDCyStqgKzIEviyBQsWIdU()  {
return ::cordl_internals::getStaticField<int32_t, "ZPbitXgDCyStqgKzIEviyBQsWIdU", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_pAZSEgPoxuDJbhwDRNOGnXvmuWPX(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "pAZSEgPoxuDJbhwDRNOGnXvmuWPX", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_pAZSEgPoxuDJbhwDRNOGnXvmuWPX()  {
return ::cordl_internals::getStaticField<int32_t, "pAZSEgPoxuDJbhwDRNOGnXvmuWPX", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_izXAAXHlBqivBcIvhpMpCPDReIFAb(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "izXAAXHlBqivBcIvhpMpCPDReIFAb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_izXAAXHlBqivBcIvhpMpCPDReIFAb()  {
return ::cordl_internals::getStaticField<int32_t, "izXAAXHlBqivBcIvhpMpCPDReIFAb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_TmFaXjBeFpLXZFTxOmoICoqbFHIy(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "TmFaXjBeFpLXZFTxOmoICoqbFHIy", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_TmFaXjBeFpLXZFTxOmoICoqbFHIy()  {
return ::cordl_internals::getStaticField<int32_t, "TmFaXjBeFpLXZFTxOmoICoqbFHIy", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_YIVrTHbycJJskQAMRLwUzgXbQjSu(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "YIVrTHbycJJskQAMRLwUzgXbQjSu", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_YIVrTHbycJJskQAMRLwUzgXbQjSu()  {
return ::cordl_internals::getStaticField<int32_t, "YIVrTHbycJJskQAMRLwUzgXbQjSu", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_XOpdwMcGXfLFexDYTUFjAUsCYJlj(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "XOpdwMcGXfLFexDYTUFjAUsCYJlj", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_XOpdwMcGXfLFexDYTUFjAUsCYJlj()  {
return ::cordl_internals::getStaticField<int32_t, "XOpdwMcGXfLFexDYTUFjAUsCYJlj", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_KjdBtFhcVEmlfBMMlSjqMBYTgDJRA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "KjdBtFhcVEmlfBMMlSjqMBYTgDJRA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_KjdBtFhcVEmlfBMMlSjqMBYTgDJRA()  {
return ::cordl_internals::getStaticField<int32_t, "KjdBtFhcVEmlfBMMlSjqMBYTgDJRA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_HOVjhuUkhucpDamozGssUSuWEiOQ(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "HOVjhuUkhucpDamozGssUSuWEiOQ", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_HOVjhuUkhucpDamozGssUSuWEiOQ()  {
return ::cordl_internals::getStaticField<int32_t, "HOVjhuUkhucpDamozGssUSuWEiOQ", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_iduDJTWbUecmLaSvhbYyznBSFapbb(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "iduDJTWbUecmLaSvhbYyznBSFapbb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_iduDJTWbUecmLaSvhbYyznBSFapbb()  {
return ::cordl_internals::getStaticField<int32_t, "iduDJTWbUecmLaSvhbYyznBSFapbb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_AbJNnBTXcLSBpYoSQgDHOzbFPjAd(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "AbJNnBTXcLSBpYoSQgDHOzbFPjAd", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_AbJNnBTXcLSBpYoSQgDHOzbFPjAd()  {
return ::cordl_internals::getStaticField<int32_t, "AbJNnBTXcLSBpYoSQgDHOzbFPjAd", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_epqKUzzUERuYFVscKHIaqEDSrsWR(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "epqKUzzUERuYFVscKHIaqEDSrsWR", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_epqKUzzUERuYFVscKHIaqEDSrsWR()  {
return ::cordl_internals::getStaticField<int32_t, "epqKUzzUERuYFVscKHIaqEDSrsWR", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_AKqoYkfMigxuNkZHDSihgWoEDNLO(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "AKqoYkfMigxuNkZHDSihgWoEDNLO", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_AKqoYkfMigxuNkZHDSihgWoEDNLO()  {
return ::cordl_internals::getStaticField<int32_t, "AKqoYkfMigxuNkZHDSihgWoEDNLO", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_SqPlDNqvOmQMULkQdtXWiOTZhUhF(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "SqPlDNqvOmQMULkQdtXWiOTZhUhF", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_SqPlDNqvOmQMULkQdtXWiOTZhUhF()  {
return ::cordl_internals::getStaticField<int32_t, "SqPlDNqvOmQMULkQdtXWiOTZhUhF", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_HfaPjJPgFtqrgVqARYFHwjMQHpChA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "HfaPjJPgFtqrgVqARYFHwjMQHpChA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_HfaPjJPgFtqrgVqARYFHwjMQHpChA()  {
return ::cordl_internals::getStaticField<int32_t, "HfaPjJPgFtqrgVqARYFHwjMQHpChA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_wylCSFDQhUGbskMSnbWTPmwRBbEB(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "wylCSFDQhUGbskMSnbWTPmwRBbEB", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_wylCSFDQhUGbskMSnbWTPmwRBbEB()  {
return ::cordl_internals::getStaticField<int32_t, "wylCSFDQhUGbskMSnbWTPmwRBbEB", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_dEfVDWXBtFqTYQNErEpCluhCfrvl(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "dEfVDWXBtFqTYQNErEpCluhCfrvl", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_dEfVDWXBtFqTYQNErEpCluhCfrvl()  {
return ::cordl_internals::getStaticField<int32_t, "dEfVDWXBtFqTYQNErEpCluhCfrvl", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_QNivogLWotWKjvbJgedUFmhArIxtA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "QNivogLWotWKjvbJgedUFmhArIxtA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_QNivogLWotWKjvbJgedUFmhArIxtA()  {
return ::cordl_internals::getStaticField<int32_t, "QNivogLWotWKjvbJgedUFmhArIxtA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_RXGfpPeauUWipNloqrxfJXEcuhZW(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "RXGfpPeauUWipNloqrxfJXEcuhZW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_RXGfpPeauUWipNloqrxfJXEcuhZW()  {
return ::cordl_internals::getStaticField<int32_t, "RXGfpPeauUWipNloqrxfJXEcuhZW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_jXhcEtFoaWTKhiQhZfINZmtMayDW(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "jXhcEtFoaWTKhiQhZfINZmtMayDW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_jXhcEtFoaWTKhiQhZfINZmtMayDW()  {
return ::cordl_internals::getStaticField<int32_t, "jXhcEtFoaWTKhiQhZfINZmtMayDW", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_ZQADcUQCFxCrTKgtAaiSIuJJfPAHb(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "ZQADcUQCFxCrTKgtAaiSIuJJfPAHb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_ZQADcUQCFxCrTKgtAaiSIuJJfPAHb()  {
return ::cordl_internals::getStaticField<int32_t, "ZQADcUQCFxCrTKgtAaiSIuJJfPAHb", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_XrllQvxCWnWFktSvfdAxBBKKTEQG(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "XrllQvxCWnWFktSvfdAxBBKKTEQG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_XrllQvxCWnWFktSvfdAxBBKKTEQG()  {
return ::cordl_internals::getStaticField<int32_t, "XrllQvxCWnWFktSvfdAxBBKKTEQG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_yxFIgulCEIdLScRlJrnnCUDhhKVS(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "yxFIgulCEIdLScRlJrnnCUDhhKVS", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_yxFIgulCEIdLScRlJrnnCUDhhKVS()  {
return ::cordl_internals::getStaticField<int32_t, "yxFIgulCEIdLScRlJrnnCUDhhKVS", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_JWiHHlkdNOCsQqJvYkdYMFGflwzv(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "JWiHHlkdNOCsQqJvYkdYMFGflwzv", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_JWiHHlkdNOCsQqJvYkdYMFGflwzv()  {
return ::cordl_internals::getStaticField<int32_t, "JWiHHlkdNOCsQqJvYkdYMFGflwzv", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_vkaFkvxKFXwoLkKBnUPtEdEjlktO(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "vkaFkvxKFXwoLkKBnUPtEdEjlktO", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_vkaFkvxKFXwoLkKBnUPtEdEjlktO()  {
return ::cordl_internals::getStaticField<int32_t, "vkaFkvxKFXwoLkKBnUPtEdEjlktO", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_WsDVPNzjYffvZPLDTbDjnBgWQJbM(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "WsDVPNzjYffvZPLDTbDjnBgWQJbM", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_WsDVPNzjYffvZPLDTbDjnBgWQJbM()  {
return ::cordl_internals::getStaticField<int32_t, "WsDVPNzjYffvZPLDTbDjnBgWQJbM", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_LusuKtyNngmRamFHqyDijtejcwmk(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "LusuKtyNngmRamFHqyDijtejcwmk", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_LusuKtyNngmRamFHqyDijtejcwmk()  {
return ::cordl_internals::getStaticField<int32_t, "LusuKtyNngmRamFHqyDijtejcwmk", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_INLcHbikxgvXCjxxxHvfXUvMyFiM(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "INLcHbikxgvXCjxxxHvfXUvMyFiM", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_INLcHbikxgvXCjxxxHvfXUvMyFiM()  {
return ::cordl_internals::getStaticField<int32_t, "INLcHbikxgvXCjxxxHvfXUvMyFiM", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_psoxJsKqLZJMJMXRojNvJMWLerQgA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "psoxJsKqLZJMJMXRojNvJMWLerQgA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_psoxJsKqLZJMJMXRojNvJMWLerQgA()  {
return ::cordl_internals::getStaticField<int32_t, "psoxJsKqLZJMJMXRojNvJMWLerQgA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_uGWtpUGeSZkPsyfAYuxFeTqCJQRp(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "uGWtpUGeSZkPsyfAYuxFeTqCJQRp", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_uGWtpUGeSZkPsyfAYuxFeTqCJQRp()  {
return ::cordl_internals::getStaticField<int32_t, "uGWtpUGeSZkPsyfAYuxFeTqCJQRp", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_mZXMudOpxXnhxhxTmcNTJFALueCQ(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "mZXMudOpxXnhxhxTmcNTJFALueCQ", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_mZXMudOpxXnhxhxTmcNTJFALueCQ()  {
return ::cordl_internals::getStaticField<int32_t, "mZXMudOpxXnhxhxTmcNTJFALueCQ", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_dGUSuOOcqxAVxMljfjaBqVZAXsRK(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "dGUSuOOcqxAVxMljfjaBqVZAXsRK", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_dGUSuOOcqxAVxMljfjaBqVZAXsRK()  {
return ::cordl_internals::getStaticField<int32_t, "dGUSuOOcqxAVxMljfjaBqVZAXsRK", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_fxGcxGencfuORBUfwOFxWGNTkoJv(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "fxGcxGencfuORBUfwOFxWGNTkoJv", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_fxGcxGencfuORBUfwOFxWGNTkoJv()  {
return ::cordl_internals::getStaticField<int32_t, "fxGcxGencfuORBUfwOFxWGNTkoJv", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_tbwjuLEVVLvEACimRHVGKTQoLMYp(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "tbwjuLEVVLvEACimRHVGKTQoLMYp", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_tbwjuLEVVLvEACimRHVGKTQoLMYp()  {
return ::cordl_internals::getStaticField<int32_t, "tbwjuLEVVLvEACimRHVGKTQoLMYp", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_fGfqdxgbyWnjxFMZtvALZiYDcCMKA(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "fGfqdxgbyWnjxFMZtvALZiYDcCMKA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_fGfqdxgbyWnjxFMZtvALZiYDcCMKA()  {
return ::cordl_internals::getStaticField<int32_t, "fGfqdxgbyWnjxFMZtvALZiYDcCMKA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_YQpcGtiNIeeoiphCxOLOUZiSxYjS(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "YQpcGtiNIeeoiphCxOLOUZiSxYjS", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_YQpcGtiNIeeoiphCxOLOUZiSxYjS()  {
return ::cordl_internals::getStaticField<int32_t, "YQpcGtiNIeeoiphCxOLOUZiSxYjS", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_dFiSLcuoRVkarAIUlcupdXrUJKoC(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "dFiSLcuoRVkarAIUlcupdXrUJKoC", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_dFiSLcuoRVkarAIUlcupdXrUJKoC()  {
return ::cordl_internals::getStaticField<int32_t, "dFiSLcuoRVkarAIUlcupdXrUJKoC", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_WzhViiLYPcNkHQtZiJgvUsnCvIFM(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "WzhViiLYPcNkHQtZiJgvUsnCvIFM", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_WzhViiLYPcNkHQtZiJgvUsnCvIFM()  {
return ::cordl_internals::getStaticField<int32_t, "WzhViiLYPcNkHQtZiJgvUsnCvIFM", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_ewvGptcTBjudkOpbcKUpTynapQjk(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "ewvGptcTBjudkOpbcKUpTynapQjk", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_ewvGptcTBjudkOpbcKUpTynapQjk()  {
return ::cordl_internals::getStaticField<int32_t, "ewvGptcTBjudkOpbcKUpTynapQjk", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_DyhacaPggenAkPISSbstdZVpkzMV(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "DyhacaPggenAkPISSbstdZVpkzMV", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_DyhacaPggenAkPISSbstdZVpkzMV()  {
return ::cordl_internals::getStaticField<int32_t, "DyhacaPggenAkPISSbstdZVpkzMV", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_iEKPlXloLEnrZVHHjcTJJJkCujnu(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "iEKPlXloLEnrZVHHjcTJJJkCujnu", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_iEKPlXloLEnrZVHHjcTJJJkCujnu()  {
return ::cordl_internals::getStaticField<int32_t, "iEKPlXloLEnrZVHHjcTJJJkCujnu", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_vwbAblUVUuGBEgdAviyTWIwRNXZG(int32_t  value)  {
::cordl_internals::setStaticField<int32_t, "vwbAblUVUuGBEgdAviyTWIwRNXZG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<int32_t>(value));
}
inline int32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_vwbAblUVUuGBEgdAviyTWIwRNXZG()  {
return ::cordl_internals::getStaticField<int32_t, "vwbAblUVUuGBEgdAviyTWIwRNXZG", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_QsruvzqDHjlPJYVOfeaTsjONpsSU(uint32_t  value)  {
::cordl_internals::setStaticField<uint32_t, "QsruvzqDHjlPJYVOfeaTsjONpsSU", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<uint32_t>(value));
}
inline uint32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_QsruvzqDHjlPJYVOfeaTsjONpsSU()  {
return ::cordl_internals::getStaticField<uint32_t, "QsruvzqDHjlPJYVOfeaTsjONpsSU", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_eaoTrkIfpINsmpCNTylFgcqqEfeA(uint32_t  value)  {
::cordl_internals::setStaticField<uint32_t, "eaoTrkIfpINsmpCNTylFgcqqEfeA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<uint32_t>(value));
}
inline uint32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_eaoTrkIfpINsmpCNTylFgcqqEfeA()  {
return ::cordl_internals::getStaticField<uint32_t, "eaoTrkIfpINsmpCNTylFgcqqEfeA", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_oOzWvpjgfZCtDHcEyBxUkVZQikQy(uint32_t  value)  {
::cordl_internals::setStaticField<uint32_t, "oOzWvpjgfZCtDHcEyBxUkVZQikQy", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<uint32_t>(value));
}
inline uint32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_oOzWvpjgfZCtDHcEyBxUkVZQikQy()  {
return ::cordl_internals::getStaticField<uint32_t, "oOzWvpjgfZCtDHcEyBxUkVZQikQy", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_JSzEYuscTrOrEcoodaHveIDNiTNe(uint32_t  value)  {
::cordl_internals::setStaticField<uint32_t, "JSzEYuscTrOrEcoodaHveIDNiTNe", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<uint32_t>(value));
}
inline uint32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_JSzEYuscTrOrEcoodaHveIDNiTNe()  {
return ::cordl_internals::getStaticField<uint32_t, "JSzEYuscTrOrEcoodaHveIDNiTNe", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::setStaticF_lSPUTweltdVaPwfExpEZVTAAERJI(uint32_t  value)  {
::cordl_internals::setStaticField<uint32_t, "lSPUTweltdVaPwfExpEZVTAAERJI", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(std::forward<uint32_t>(value));
}
inline uint32_t GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::getStaticF_lSPUTweltdVaPwfExpEZVTAAERJI()  {
return ::cordl_internals::getStaticField<uint32_t, "lSPUTweltdVaPwfExpEZVTAAERJI", ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>();
}
inline void GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::_ctor()  {
static auto* ___internal_method = THROW_UNLESS(::i2c::no_logger{}, (::i2c::find_method(
                        ::i2c::class_of<::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>(),
                        {".ctor", {}, {}}
                    )));
return ::cordl_internals::RunMethodRethrow<void>(this, ___internal_method);
}
inline ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA* GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::New_ctor()  {
return THROW_UNLESS(::i2c::no_logger{}, ::i2c::new_ctor<::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA*>());
}
// Ctor Parameters []
constexpr ::GlobalNamespace::WBfKBBBVwYdQipIgVVLohIsYgBpdA::WBfKBBBVwYdQipIgVVLohIsYgBpdA()   {
}
