#pragma once
// IWYU pragma private; include "GlobalNamespace/MhKgXDpaAPQJjajFJDvxYgPwhffkA.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "System/zzzz__Object_def.hpp"
#include "beatsaber-hook/shared/stringw.hpp"
#include <cstdint>
CORDL_MODULE_EXPORT(MhKgXDpaAPQJjajFJDvxYgPwhffkA)
namespace GlobalNamespace {
class KlcNeaFZiwoAzlYmohbMFFSmhxYd;
}
namespace GlobalNamespace {
class ilReClayUpFdClpKxnBeDJuNJPBMA;
}
// Forward declare root types
namespace GlobalNamespace {
class MhKgXDpaAPQJjajFJDvxYgPwhffkA;
}
// Write type traits
MARK_REF_T(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA*);
DEFINE_IL2CPP_CLASS(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA*, "", "MhKgXDpaAPQJjajFJDvxYgPwhffkA");
// Dependencies System.Object
namespace GlobalNamespace {
// Is value type: false
// CS Name: MhKgXDpaAPQJjajFJDvxYgPwhffkA
class CORDL_TYPE MhKgXDpaAPQJjajFJDvxYgPwhffkA : public ::System::Object {
public:
// Declarations
/// @brief Field FNVMgueNDWFVfjqmMikjAuSoivDi, offset 0x30, size 0x8 
 __declspec(property(get=__cordl_internal_get_FNVMgueNDWFVfjqmMikjAuSoivDi, put=__cordl_internal_set_FNVMgueNDWFVfjqmMikjAuSoivDi)) ::StringW  FNVMgueNDWFVfjqmMikjAuSoivDi;

/// @brief Field JIuKsVObBKmPRBwLfLfwaAYMFGvG, offset 0x18, size 0x8 
 __declspec(property(get=__cordl_internal_get_JIuKsVObBKmPRBwLfLfwaAYMFGvG, put=__cordl_internal_set_JIuKsVObBKmPRBwLfLfwaAYMFGvG)) ::StringW  JIuKsVObBKmPRBwLfLfwaAYMFGvG;

 __declspec(property(get=hphAnMIpWRLlLsrsNOyXeLybVdAOb)) ::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd*  JqNElmmEiPPuRMrNzHiySDoxgnxs;

/// @brief Field OVAlnfhBBLcoGcLbcQyeYKClYsuPA, offset 0x20, size 0x8 
 __declspec(property(get=__cordl_internal_get_OVAlnfhBBLcoGcLbcQyeYKClYsuPA, put=__cordl_internal_set_OVAlnfhBBLcoGcLbcQyeYKClYsuPA)) ::StringW  OVAlnfhBBLcoGcLbcQyeYKClYsuPA;

/// @brief Field OfszUqfoaJVUlCVymPVBmndJXDaA, offset 0x38, size 0x4 
 __declspec(property(get=__cordl_internal_get_OfszUqfoaJVUlCVymPVBmndJXDaA, put=__cordl_internal_set_OfszUqfoaJVUlCVymPVBmndJXDaA)) int32_t  OfszUqfoaJVUlCVymPVBmndJXDaA;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_autoGeneratedValueFlags, put=Rewired_Internal_Localization_INameLocalizerSource_set_autoGeneratedValueFlags)) int32_t  Rewired_Internal_Localization_INameLocalizerSource_autoGeneratedValueFlags;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_key)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_key;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_keyCategory)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_keyCategory;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_nonLocalizedDescriptiveName, put=Rewired_Internal_Localization_INameLocalizerSource_set_nonLocalizedDescriptiveName)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_nonLocalizedDescriptiveName;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_scriptingName)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_scriptingName;

/// @brief Field UGrjQtVgDeKCLAvfyGSYTFEVgtyjA, offset 0x28, size 0x8 
 __declspec(property(get=__cordl_internal_get_UGrjQtVgDeKCLAvfyGSYTFEVgtyjA, put=__cordl_internal_set_UGrjQtVgDeKCLAvfyGSYTFEVgtyjA)) ::StringW  UGrjQtVgDeKCLAvfyGSYTFEVgtyjA;

/// @brief Field acINatwRXCxfrLNVCDSrEYRXYxsf, offset 0x10, size 0x8 
 __declspec(property(get=__cordl_internal_get_acINatwRXCxfrLNVCDSrEYRXYxsf, put=__cordl_internal_set_acINatwRXCxfrLNVCDSrEYRXYxsf)) ::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd*  acINatwRXCxfrLNVCDSrEYRXYxsf;

 __declspec(property(get=FUbzstdtrpamXNiBHRlkwLRiqOfP)) ::StringW  cRPGEIPCCOiLSKiSCBpreHxBkcvpb;

 __declspec(property(get=get_key)) ::StringW  key;

 __declspec(property(get=get_keyCategory)) ::StringW  keyCategory;

 __declspec(property(get=get_nonLocalizedDescriptiveName)) ::StringW  nonLocalizedDescriptiveName;

 __declspec(property(get=get_scriptingName)) ::StringW  scriptingName;

/// @brief Convert operator to "::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA"
constexpr operator  ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*() noexcept;

/// @brief Method FUbzstdtrpamXNiBHRlkwLRiqOfP, addr 0x1818f3840, size 0x50, virtual false, abstract: false, final false
inline ::StringW FUbzstdtrpamXNiBHRlkwLRiqOfP() ;

/// @brief Method GjNyUvYcsALgidNbNOjebRRPbdEAA, addr 0x1818f3890, size 0xa0, virtual true, abstract: false, final false
inline bool GjNyUvYcsALgidNbNOjebRRPbdEAA(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA*  _cordl_fixed_empty_name_whitespace, bool  _cordl_fixed_empty_name_whitespace_param_1) ;

static inline ::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA* New_ctor(::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd*  _cordl_fixed_empty_name_whitespace, ::StringW  _cordl_fixed_empty_name_whitespace_param_1, ::StringW  _cordl_fixed_empty_name_whitespace_param_2, ::StringW  _cordl_fixed_empty_name_whitespace_param_3, ::StringW  _cordl_fixed_empty_name_whitespace_param_4) ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_autoGeneratedValueFlags, addr 0x180392fe0, size 0x10, virtual true, abstract: false, final true
inline int32_t Rewired_Internal_Localization_INameLocalizerSource_get_autoGeneratedValueFlags() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_key, addr 0x1802d97f0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_key() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_keyCategory, addr 0x1802ecc10, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_keyCategory() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_nonLocalizedDescriptiveName, addr 0x1802d9810, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_nonLocalizedDescriptiveName() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_scriptingName, addr 0x1802d97e0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_scriptingName() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.set_autoGeneratedValueFlags, addr 0x180393000, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_INameLocalizerSource_set_autoGeneratedValueFlags(int32_t  value) ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.set_nonLocalizedDescriptiveName, addr 0x1802d9850, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_INameLocalizerSource_set_nonLocalizedDescriptiveName(::StringW  value) ;

constexpr ::StringW const& __cordl_internal_get_FNVMgueNDWFVfjqmMikjAuSoivDi() const;

constexpr ::StringW& __cordl_internal_get_FNVMgueNDWFVfjqmMikjAuSoivDi() ;

constexpr ::StringW const& __cordl_internal_get_JIuKsVObBKmPRBwLfLfwaAYMFGvG() const;

constexpr ::StringW& __cordl_internal_get_JIuKsVObBKmPRBwLfLfwaAYMFGvG() ;

constexpr ::StringW const& __cordl_internal_get_OVAlnfhBBLcoGcLbcQyeYKClYsuPA() const;

constexpr ::StringW& __cordl_internal_get_OVAlnfhBBLcoGcLbcQyeYKClYsuPA() ;

constexpr int32_t const& __cordl_internal_get_OfszUqfoaJVUlCVymPVBmndJXDaA() const;

constexpr int32_t& __cordl_internal_get_OfszUqfoaJVUlCVymPVBmndJXDaA() ;

constexpr ::StringW const& __cordl_internal_get_UGrjQtVgDeKCLAvfyGSYTFEVgtyjA() const;

constexpr ::StringW& __cordl_internal_get_UGrjQtVgDeKCLAvfyGSYTFEVgtyjA() ;

constexpr ::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd* const& __cordl_internal_get_acINatwRXCxfrLNVCDSrEYRXYxsf() const;

constexpr ::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd*& __cordl_internal_get_acINatwRXCxfrLNVCDSrEYRXYxsf() ;

constexpr void __cordl_internal_set_FNVMgueNDWFVfjqmMikjAuSoivDi(::StringW  value) ;

constexpr void __cordl_internal_set_JIuKsVObBKmPRBwLfLfwaAYMFGvG(::StringW  value) ;

constexpr void __cordl_internal_set_OVAlnfhBBLcoGcLbcQyeYKClYsuPA(::StringW  value) ;

constexpr void __cordl_internal_set_OfszUqfoaJVUlCVymPVBmndJXDaA(int32_t  value) ;

constexpr void __cordl_internal_set_UGrjQtVgDeKCLAvfyGSYTFEVgtyjA(::StringW  value) ;

constexpr void __cordl_internal_set_acINatwRXCxfrLNVCDSrEYRXYxsf(::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd*  value) ;

/// @brief Method .ctor, addr 0x1818f3930, size 0xb0, virtual false, abstract: false, final false
inline void _ctor(::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd*  _cordl_fixed_empty_name_whitespace, ::StringW  _cordl_fixed_empty_name_whitespace_param_1, ::StringW  _cordl_fixed_empty_name_whitespace_param_2, ::StringW  _cordl_fixed_empty_name_whitespace_param_3, ::StringW  _cordl_fixed_empty_name_whitespace_param_4) ;

/// @brief Method get_key, addr 0x1802d97f0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_key() ;

/// @brief Method get_keyCategory, addr 0x1802ecc10, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_keyCategory() ;

/// @brief Method get_nonLocalizedDescriptiveName, addr 0x1802d9810, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_nonLocalizedDescriptiveName() ;

/// @brief Method get_scriptingName, addr 0x1802d97e0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_scriptingName() ;

/// @brief Method hphAnMIpWRLlLsrsNOyXeLybVdAOb, addr 0x1802db4a0, size 0x10, virtual false, abstract: false, final false
inline ::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd* hphAnMIpWRLlLsrsNOyXeLybVdAOb() ;

/// @brief Convert to "::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA"
constexpr ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA* i___GlobalNamespace__ilReClayUpFdClpKxnBeDJuNJPBMA() noexcept;

protected:
// Ctor Parameters []
// @brief default ctor
constexpr MhKgXDpaAPQJjajFJDvxYgPwhffkA() ;
public:

// Ctor Parameters [CppParam { name: "", ty: "MhKgXDpaAPQJjajFJDvxYgPwhffkA", modifiers: "&&", def_value: None }]
// @brief delete move ctor to prevent accidental deref moves
MhKgXDpaAPQJjajFJDvxYgPwhffkA(MhKgXDpaAPQJjajFJDvxYgPwhffkA && ) = delete;

// Ctor Parameters [CppParam { name: "", ty: "MhKgXDpaAPQJjajFJDvxYgPwhffkA", modifiers: "const&", def_value: None }]
// @brief delete copy ctor to prevent accidental deref copies
MhKgXDpaAPQJjajFJDvxYgPwhffkA(MhKgXDpaAPQJjajFJDvxYgPwhffkA const& ) = delete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{2852};

/// @brief Field acINatwRXCxfrLNVCDSrEYRXYxsf, offset: 0x10, size: 0x8, def value: None
 ::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd*  ___acINatwRXCxfrLNVCDSrEYRXYxsf;

/// @brief Field JIuKsVObBKmPRBwLfLfwaAYMFGvG, offset: 0x18, size: 0x8, def value: None
 ::StringW  ___JIuKsVObBKmPRBwLfLfwaAYMFGvG;

/// @brief Field OVAlnfhBBLcoGcLbcQyeYKClYsuPA, offset: 0x20, size: 0x8, def value: None
 ::StringW  ___OVAlnfhBBLcoGcLbcQyeYKClYsuPA;

/// @brief Field UGrjQtVgDeKCLAvfyGSYTFEVgtyjA, offset: 0x28, size: 0x8, def value: None
 ::StringW  ___UGrjQtVgDeKCLAvfyGSYTFEVgtyjA;

/// @brief Field FNVMgueNDWFVfjqmMikjAuSoivDi, offset: 0x30, size: 0x8, def value: None
 ::StringW  ___FNVMgueNDWFVfjqmMikjAuSoivDi;

/// @brief Field OfszUqfoaJVUlCVymPVBmndJXDaA, offset: 0x38, size: 0x4, def value: None
 int32_t  ___OfszUqfoaJVUlCVymPVBmndJXDaA;

static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
static_assert(offsetof(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA, ___acINatwRXCxfrLNVCDSrEYRXYxsf) == 0x10, "Offset mismatch!");

static_assert(offsetof(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA, ___JIuKsVObBKmPRBwLfLfwaAYMFGvG) == 0x18, "Offset mismatch!");

static_assert(offsetof(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA, ___OVAlnfhBBLcoGcLbcQyeYKClYsuPA) == 0x20, "Offset mismatch!");

static_assert(offsetof(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA, ___UGrjQtVgDeKCLAvfyGSYTFEVgtyjA) == 0x28, "Offset mismatch!");

static_assert(offsetof(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA, ___FNVMgueNDWFVfjqmMikjAuSoivDi) == 0x30, "Offset mismatch!");

static_assert(offsetof(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA, ___OfszUqfoaJVUlCVymPVBmndJXDaA) == 0x38, "Offset mismatch!");

static_assert(sizeof(::GlobalNamespace::MhKgXDpaAPQJjajFJDvxYgPwhffkA) == 0x40, "Size mismatch!");

} // namespace end def GlobalNamespace
