#pragma once
// IWYU pragma private; include "Rewired/InputLayout.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "System/zzzz__Object_def.hpp"
#include "beatsaber-hook/shared/stringw.hpp"
#include <cstdint>
CORDL_MODULE_EXPORT(InputLayout)
namespace GlobalNamespace {
class ilReClayUpFdClpKxnBeDJuNJPBMA;
}
namespace GlobalNamespace {
class vKlxFVEhQCQotaZlQCGnJzUBdQtQ;
}
// Forward declare root types
namespace Rewired {
class InputLayout;
}
// Write type traits
MARK_REF_T(::Rewired::InputLayout*);
DEFINE_IL2CPP_CLASS(::Rewired::InputLayout*, "Rewired", "InputLayout");
// Dependencies System.Object
namespace Rewired {
// Is value type: false
// CS Name: Rewired.InputLayout
class CORDL_TYPE InputLayout : public ::System::Object {
public:
// Declarations
 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_autoGeneratedValueFlags, put=Rewired_Internal_Localization_INameLocalizerSource_set_autoGeneratedValueFlags)) int32_t  Rewired_Internal_Localization_INameLocalizerSource_autoGeneratedValueFlags;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_key)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_key;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_keyCategory)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_keyCategory;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_nonLocalizedDescriptiveName, put=Rewired_Internal_Localization_INameLocalizerSource_set_nonLocalizedDescriptiveName)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_nonLocalizedDescriptiveName;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_scriptingName)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_scriptingName;

/// @brief Field TeRYfGXXpplGDKxeVXQToFqDDiIe, offset 0x38, size 0x4 
 __declspec(property(get=__cordl_internal_get_TeRYfGXXpplGDKxeVXQToFqDDiIe, put=__cordl_internal_set_TeRYfGXXpplGDKxeVXQToFqDDiIe)) int32_t  TeRYfGXXpplGDKxeVXQToFqDDiIe;

/// @brief Field _descriptiveName, offset 0x18, size 0x8 
 __declspec(property(get=__cordl_internal_get__descriptiveName, put=__cordl_internal_set__descriptiveName)) ::StringW  _descriptiveName;

/// @brief Field _id, offset 0x28, size 0x4 
 __declspec(property(get=__cordl_internal_get__id, put=__cordl_internal_set__id)) int32_t  _id;

/// @brief Field _key, offset 0x20, size 0x8 
 __declspec(property(get=__cordl_internal_get__key, put=__cordl_internal_set__key)) ::StringW  _key;

/// @brief Field _name, offset 0x10, size 0x8 
 __declspec(property(get=__cordl_internal_get__name, put=__cordl_internal_set__name)) ::StringW  _name;

 __declspec(property(get=get_descriptiveName, put=poIEyQpavGuKVyhByAdCGpMHaAGI)) ::StringW  descriptiveName;

 __declspec(property(get=get_id, put=SHInxCAbgTCwLUhIbAMQbOrAFjoV)) int32_t  id;

 __declspec(property(get=get_key, put=set_key)) ::StringW  key;

 __declspec(property(get=get_name, put=LkDWGxGCPdkXoyKFYdMFytXgxZCh)) ::StringW  name;

 __declspec(property(get=get_nonLocalizedDescriptiveName, put=set_nonLocalizedDescriptiveName)) ::StringW  nonLocalizedDescriptiveName;

/// @brief Field qEALLZXhknqUkRUhWarXSNwpIPIy, offset 0x30, size 0x8 
 __declspec(property(get=__cordl_internal_get_qEALLZXhknqUkRUhWarXSNwpIPIy, put=__cordl_internal_set_qEALLZXhknqUkRUhWarXSNwpIPIy)) ::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ*  qEALLZXhknqUkRUhWarXSNwpIPIy;

/// @brief Convert operator to "::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA"
constexpr operator  ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*() noexcept;

/// @brief Method Clone, addr 0x1819a54d0, size 0x80, virtual false, abstract: false, final false
inline ::Rewired::InputLayout* Clone() ;

/// @brief Method LkDWGxGCPdkXoyKFYdMFytXgxZCh, addr 0x180308500, size 0x30, virtual false, abstract: false, final false
inline void LkDWGxGCPdkXoyKFYdMFytXgxZCh(::StringW  _cordl_fixed_empty_name_whitespace) ;

static inline ::Rewired::InputLayout* New_ctor() ;

static inline ::Rewired::InputLayout* New_ctor(::Rewired::InputLayout*  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_autoGeneratedValueFlags, addr 0x180392fe0, size 0x10, virtual true, abstract: false, final true
inline int32_t Rewired_Internal_Localization_INameLocalizerSource_get_autoGeneratedValueFlags() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_key, addr 0x1802d97e0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_key() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_keyCategory, addr 0x1819a5550, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_keyCategory() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_nonLocalizedDescriptiveName, addr 0x1802ecc10, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_nonLocalizedDescriptiveName() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_scriptingName, addr 0x1802db4a0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_scriptingName() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.set_autoGeneratedValueFlags, addr 0x180393000, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_INameLocalizerSource_set_autoGeneratedValueFlags(int32_t  value) ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.set_nonLocalizedDescriptiveName, addr 0x1802ecc20, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_INameLocalizerSource_set_nonLocalizedDescriptiveName(::StringW  value) ;

/// @brief Method SHInxCAbgTCwLUhIbAMQbOrAFjoV, addr 0x1803914c0, size 0x10, virtual false, abstract: false, final false
inline void SHInxCAbgTCwLUhIbAMQbOrAFjoV(int32_t  _cordl_fixed_empty_name_whitespace) ;

constexpr int32_t const& __cordl_internal_get_TeRYfGXXpplGDKxeVXQToFqDDiIe() const;

constexpr int32_t& __cordl_internal_get_TeRYfGXXpplGDKxeVXQToFqDDiIe() ;

constexpr ::StringW const& __cordl_internal_get__descriptiveName() const;

constexpr ::StringW& __cordl_internal_get__descriptiveName() ;

constexpr int32_t const& __cordl_internal_get__id() const;

constexpr int32_t& __cordl_internal_get__id() ;

constexpr ::StringW const& __cordl_internal_get__key() const;

constexpr ::StringW& __cordl_internal_get__key() ;

constexpr ::StringW const& __cordl_internal_get__name() const;

constexpr ::StringW& __cordl_internal_get__name() ;

constexpr ::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ* const& __cordl_internal_get_qEALLZXhknqUkRUhWarXSNwpIPIy() const;

constexpr ::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ*& __cordl_internal_get_qEALLZXhknqUkRUhWarXSNwpIPIy() ;

constexpr void __cordl_internal_set_TeRYfGXXpplGDKxeVXQToFqDDiIe(int32_t  value) ;

constexpr void __cordl_internal_set__descriptiveName(::StringW  value) ;

constexpr void __cordl_internal_set__id(int32_t  value) ;

constexpr void __cordl_internal_set__key(::StringW  value) ;

constexpr void __cordl_internal_set__name(::StringW  value) ;

constexpr void __cordl_internal_set_qEALLZXhknqUkRUhWarXSNwpIPIy(::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ*  value) ;

/// @brief Method .ctor, addr 0x1802d9d80, size 0x10, virtual false, abstract: false, final false
inline void _ctor() ;

/// @brief Method .ctor, addr 0x1819a5560, size 0x70, virtual false, abstract: false, final false
inline void _ctor(::Rewired::InputLayout*  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method ewLMXXZZcSMzspBRvOjCOilSrKdk, addr 0x1802d9d80, size 0x10, virtual false, abstract: false, final false
inline void ewLMXXZZcSMzspBRvOjCOilSrKdk() ;

/// @brief Method get_descriptiveName, addr 0x1819a55d0, size 0x90, virtual false, abstract: false, final false
inline ::StringW get_descriptiveName() ;

/// @brief Method get_id, addr 0x1803914a0, size 0x10, virtual false, abstract: false, final false
inline int32_t get_id() ;

/// @brief Method get_key, addr 0x1802d97e0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_key() ;

/// @brief Method get_name, addr 0x1802db4a0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_name() ;

/// @brief Method get_nonLocalizedDescriptiveName, addr 0x1802ecc10, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_nonLocalizedDescriptiveName() ;

/// @brief Convert to "::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA"
constexpr ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA* i___GlobalNamespace__ilReClayUpFdClpKxnBeDJuNJPBMA() noexcept;

/// @brief Method poIEyQpavGuKVyhByAdCGpMHaAGI, addr 0x1819a5660, size 0x90, virtual false, abstract: false, final false
inline void poIEyQpavGuKVyhByAdCGpMHaAGI(::StringW  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method set_key, addr 0x1819a56f0, size 0x90, virtual false, abstract: false, final false
inline void set_key(::StringW  value) ;

/// @brief Method set_nonLocalizedDescriptiveName, addr 0x1819a5660, size 0x90, virtual false, abstract: false, final false
inline void set_nonLocalizedDescriptiveName(::StringW  value) ;

/// @brief Method zAKrUYMlQaBFXDcLFhACgLAWEphBA, addr 0x1819a5780, size 0x30, virtual false, abstract: false, final false
inline void zAKrUYMlQaBFXDcLFhACgLAWEphBA() ;

protected:
// Ctor Parameters []
// @brief default ctor
constexpr InputLayout() ;
public:

// Ctor Parameters [CppParam { name: "", ty: "InputLayout", modifiers: "&&", def_value: None }]
// @brief delete move ctor to prevent accidental deref moves
InputLayout(InputLayout && ) = delete;

// Ctor Parameters [CppParam { name: "", ty: "InputLayout", modifiers: "const&", def_value: None }]
// @brief delete copy ctor to prevent accidental deref copies
InputLayout(InputLayout const& ) = delete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{2079};

/// @brief Field keyCategory offset 0xffffffff size 0x8
static constexpr ::ConstString  keyCategory{u"controller_map/layout"};

/// @brief Field _name, offset: 0x10, size: 0x8, def value: None
 ::StringW  ____name;

/// @brief Field _descriptiveName, offset: 0x18, size: 0x8, def value: None
 ::StringW  ____descriptiveName;

/// @brief Field _key, offset: 0x20, size: 0x8, def value: None
 ::StringW  ____key;

/// @brief Field _id, offset: 0x28, size: 0x4, def value: None
 int32_t  ____id;

/// @brief Field qEALLZXhknqUkRUhWarXSNwpIPIy, offset: 0x30, size: 0x8, def value: None
 ::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ*  ___qEALLZXhknqUkRUhWarXSNwpIPIy;

/// @brief Field TeRYfGXXpplGDKxeVXQToFqDDiIe, offset: 0x38, size: 0x4, def value: None
 int32_t  ___TeRYfGXXpplGDKxeVXQToFqDDiIe;

static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
static_assert(offsetof(::Rewired::InputLayout, ____name) == 0x10, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputLayout, ____descriptiveName) == 0x18, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputLayout, ____key) == 0x20, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputLayout, ____id) == 0x28, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputLayout, ___qEALLZXhknqUkRUhWarXSNwpIPIy) == 0x30, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputLayout, ___TeRYfGXXpplGDKxeVXQToFqDDiIe) == 0x38, "Offset mismatch!");

static_assert(sizeof(::Rewired::InputLayout) == 0x40, "Size mismatch!");

} // namespace end def Rewired
