#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Epic/OnlineServices/TitleStorage/CopyFileMetadataAtIndexOptions.hpp"
#include "Epic/OnlineServices/TitleStorage/CopyFileMetadataAtIndexOptionsInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/CopyFileMetadataByFilenameOptions.hpp"
#include "Epic/OnlineServices/TitleStorage/CopyFileMetadataByFilenameOptionsInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/DeleteCacheCallbackInfo.hpp"
#include "Epic/OnlineServices/TitleStorage/DeleteCacheCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/DeleteCacheOptions.hpp"
#include "Epic/OnlineServices/TitleStorage/DeleteCacheOptionsInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/FileMetadata.hpp"
#include "Epic/OnlineServices/TitleStorage/FileMetadataInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/FileTransferProgressCallbackInfo.hpp"
#include "Epic/OnlineServices/TitleStorage/FileTransferProgressCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/GetFileMetadataCountOptions.hpp"
#include "Epic/OnlineServices/TitleStorage/GetFileMetadataCountOptionsInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/OnDeleteCacheCompleteCallback.hpp"
#include "Epic/OnlineServices/TitleStorage/OnDeleteCacheCompleteCallbackInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/OnDeleteCacheCompleteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/TitleStorage/OnFileTransferProgressCallback.hpp"
#include "Epic/OnlineServices/TitleStorage/OnFileTransferProgressCallbackInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/OnFileTransferProgressCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/TitleStorage/OnQueryFileCompleteCallback.hpp"
#include "Epic/OnlineServices/TitleStorage/OnQueryFileCompleteCallbackInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/OnQueryFileCompleteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/TitleStorage/OnQueryFileListCompleteCallback.hpp"
#include "Epic/OnlineServices/TitleStorage/OnQueryFileListCompleteCallbackInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/OnQueryFileListCompleteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/TitleStorage/OnReadFileCompleteCallback.hpp"
#include "Epic/OnlineServices/TitleStorage/OnReadFileCompleteCallbackInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/OnReadFileCompleteCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/TitleStorage/OnReadFileDataCallback.hpp"
#include "Epic/OnlineServices/TitleStorage/OnReadFileDataCallbackInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/OnReadFileDataCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/TitleStorage/QueryFileCallbackInfo.hpp"
#include "Epic/OnlineServices/TitleStorage/QueryFileCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/QueryFileListCallbackInfo.hpp"
#include "Epic/OnlineServices/TitleStorage/QueryFileListCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/QueryFileListOptions.hpp"
#include "Epic/OnlineServices/TitleStorage/QueryFileListOptionsInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/QueryFileOptions.hpp"
#include "Epic/OnlineServices/TitleStorage/QueryFileOptionsInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/ReadFileCallbackInfo.hpp"
#include "Epic/OnlineServices/TitleStorage/ReadFileCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/ReadFileDataCallbackInfo.hpp"
#include "Epic/OnlineServices/TitleStorage/ReadFileDataCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/ReadFileOptions.hpp"
#include "Epic/OnlineServices/TitleStorage/ReadFileOptionsInternal.hpp"
#include "Epic/OnlineServices/TitleStorage/ReadResult.hpp"
#include "Epic/OnlineServices/TitleStorage/TitleStorageFileTransferRequest.hpp"
#include "Epic/OnlineServices/TitleStorage/TitleStorageInterface.hpp"
#ifdef __cpp_modules
                    export module TitleStorage;
                    #endif
                
