#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Epic/OnlineServices/KWS/AddNotifyPermissionsUpdateReceivedOptions.hpp"
#include "Epic/OnlineServices/KWS/AddNotifyPermissionsUpdateReceivedOptionsInternal.hpp"
#include "Epic/OnlineServices/KWS/CopyPermissionByIndexOptions.hpp"
#include "Epic/OnlineServices/KWS/CopyPermissionByIndexOptionsInternal.hpp"
#include "Epic/OnlineServices/KWS/CreateUserCallbackInfo.hpp"
#include "Epic/OnlineServices/KWS/CreateUserCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/KWS/CreateUserOptions.hpp"
#include "Epic/OnlineServices/KWS/CreateUserOptionsInternal.hpp"
#include "Epic/OnlineServices/KWS/GetPermissionByKeyOptions.hpp"
#include "Epic/OnlineServices/KWS/GetPermissionByKeyOptionsInternal.hpp"
#include "Epic/OnlineServices/KWS/GetPermissionsCountOptions.hpp"
#include "Epic/OnlineServices/KWS/GetPermissionsCountOptionsInternal.hpp"
#include "Epic/OnlineServices/KWS/KWSInterface.hpp"
#include "Epic/OnlineServices/KWS/KWSPermissionStatus.hpp"
#include "Epic/OnlineServices/KWS/OnCreateUserCallback.hpp"
#include "Epic/OnlineServices/KWS/OnCreateUserCallbackInternal.hpp"
#include "Epic/OnlineServices/KWS/OnCreateUserCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/KWS/OnPermissionsUpdateReceivedCallback.hpp"
#include "Epic/OnlineServices/KWS/OnPermissionsUpdateReceivedCallbackInternal.hpp"
#include "Epic/OnlineServices/KWS/OnPermissionsUpdateReceivedCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/KWS/OnQueryAgeGateCallback.hpp"
#include "Epic/OnlineServices/KWS/OnQueryAgeGateCallbackInternal.hpp"
#include "Epic/OnlineServices/KWS/OnQueryAgeGateCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/KWS/OnQueryPermissionsCallback.hpp"
#include "Epic/OnlineServices/KWS/OnQueryPermissionsCallbackInternal.hpp"
#include "Epic/OnlineServices/KWS/OnQueryPermissionsCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/KWS/OnRequestPermissionsCallback.hpp"
#include "Epic/OnlineServices/KWS/OnRequestPermissionsCallbackInternal.hpp"
#include "Epic/OnlineServices/KWS/OnRequestPermissionsCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/KWS/OnUpdateParentEmailCallback.hpp"
#include "Epic/OnlineServices/KWS/OnUpdateParentEmailCallbackInternal.hpp"
#include "Epic/OnlineServices/KWS/OnUpdateParentEmailCallbackInternalImplementation.hpp"
#include "Epic/OnlineServices/KWS/PermissionStatus.hpp"
#include "Epic/OnlineServices/KWS/PermissionStatusInternal.hpp"
#include "Epic/OnlineServices/KWS/PermissionsUpdateReceivedCallbackInfo.hpp"
#include "Epic/OnlineServices/KWS/PermissionsUpdateReceivedCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/KWS/QueryAgeGateCallbackInfo.hpp"
#include "Epic/OnlineServices/KWS/QueryAgeGateCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/KWS/QueryAgeGateOptions.hpp"
#include "Epic/OnlineServices/KWS/QueryAgeGateOptionsInternal.hpp"
#include "Epic/OnlineServices/KWS/QueryPermissionsCallbackInfo.hpp"
#include "Epic/OnlineServices/KWS/QueryPermissionsCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/KWS/QueryPermissionsOptions.hpp"
#include "Epic/OnlineServices/KWS/QueryPermissionsOptionsInternal.hpp"
#include "Epic/OnlineServices/KWS/RequestPermissionsCallbackInfo.hpp"
#include "Epic/OnlineServices/KWS/RequestPermissionsCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/KWS/RequestPermissionsOptions.hpp"
#include "Epic/OnlineServices/KWS/RequestPermissionsOptionsInternal.hpp"
#include "Epic/OnlineServices/KWS/UpdateParentEmailCallbackInfo.hpp"
#include "Epic/OnlineServices/KWS/UpdateParentEmailCallbackInfoInternal.hpp"
#include "Epic/OnlineServices/KWS/UpdateParentEmailOptions.hpp"
#include "Epic/OnlineServices/KWS/UpdateParentEmailOptionsInternal.hpp"
#ifdef __cpp_modules
                    export module KWS;
                    #endif
                
