#pragma once
// IWYU pragma private; include "Rewired/InputCategory.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "System/zzzz__Object_def.hpp"
#include "beatsaber-hook/shared/stringw.hpp"
#include <cstdint>
CORDL_MODULE_EXPORT(InputCategory)
namespace GlobalNamespace {
class ilReClayUpFdClpKxnBeDJuNJPBMA;
}
namespace GlobalNamespace {
class vKlxFVEhQCQotaZlQCGnJzUBdQtQ;
}
// Forward declare root types
namespace Rewired {
class InputCategory;
}
// Write type traits
MARK_REF_T(::Rewired::InputCategory*);
DEFINE_IL2CPP_CLASS(::Rewired::InputCategory*, "Rewired", "InputCategory");
// Dependencies System.Object
namespace Rewired {
// Is value type: false
// CS Name: Rewired.InputCategory
class CORDL_TYPE InputCategory : public ::System::Object {
public:
// Declarations
 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_autoGeneratedValueFlags, put=Rewired_Internal_Localization_INameLocalizerSource_set_autoGeneratedValueFlags)) int32_t  Rewired_Internal_Localization_INameLocalizerSource_autoGeneratedValueFlags;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_key)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_key;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_keyCategory)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_keyCategory;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_nonLocalizedDescriptiveName, put=Rewired_Internal_Localization_INameLocalizerSource_set_nonLocalizedDescriptiveName)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_nonLocalizedDescriptiveName;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_scriptingName)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_scriptingName;

/// @brief Field _descriptiveName, offset 0x18, size 0x8 
 __declspec(property(get=__cordl_internal_get__descriptiveName, put=__cordl_internal_set__descriptiveName)) ::StringW  _descriptiveName;

/// @brief Field _id, offset 0x30, size 0x4 
 __declspec(property(get=__cordl_internal_get__id, put=__cordl_internal_set__id)) int32_t  _id;

/// @brief Field _key, offset 0x20, size 0x8 
 __declspec(property(get=__cordl_internal_get__key, put=__cordl_internal_set__key)) ::StringW  _key;

/// @brief Field _name, offset 0x10, size 0x8 
 __declspec(property(get=__cordl_internal_get__name, put=__cordl_internal_set__name)) ::StringW  _name;

/// @brief Field _tag, offset 0x28, size 0x8 
 __declspec(property(get=__cordl_internal_get__tag, put=__cordl_internal_set__tag)) ::StringW  _tag;

/// @brief Field _userAssignable, offset 0x34, size 0x1 
 __declspec(property(get=__cordl_internal_get__userAssignable, put=__cordl_internal_set__userAssignable)) bool  _userAssignable;

 __declspec(property(get=get_descriptiveName, put=dCjnJOIdlsmskHqZRhLbeUuQRzbo)) ::StringW  descriptiveName;

/// @brief Field eunPorGirRtQCNqohfdyruBJnrTm, offset 0x40, size 0x4 
 __declspec(property(get=__cordl_internal_get_eunPorGirRtQCNqohfdyruBJnrTm, put=__cordl_internal_set_eunPorGirRtQCNqohfdyruBJnrTm)) int32_t  eunPorGirRtQCNqohfdyruBJnrTm;

/// @brief Field iTSyCBIXSpclRYBgrRqzlsERkHmP, offset 0x38, size 0x8 
 __declspec(property(get=__cordl_internal_get_iTSyCBIXSpclRYBgrRqzlsERkHmP, put=__cordl_internal_set_iTSyCBIXSpclRYBgrRqzlsERkHmP)) ::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ*  iTSyCBIXSpclRYBgrRqzlsERkHmP;

 __declspec(property(get=get_id, put=euDEcCRNCLyCyycWzhuPUCzRohwN)) int32_t  id;

 __declspec(property(get=get_key, put=set_key)) ::StringW  key;

 __declspec(property(get=get_keyCategory)) ::StringW  keyCategory;

 __declspec(property(get=get_name, put=UmikgmkPBmgwTCOmEOxqIKoIMcmqA)) ::StringW  name;

 __declspec(property(get=get_nonLocalizedDescriptiveName, put=set_nonLocalizedDescriptiveName)) ::StringW  nonLocalizedDescriptiveName;

 __declspec(property(get=get_tag, put=wlUujZefviMZbATAxmxOSvHqFhaO)) ::StringW  tag;

 __declspec(property(get=get_userAssignable, put=ABlRPBvRzZmfslupWjSWCJkYRdVF)) bool  userAssignable;

/// @brief Convert operator to "::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA"
constexpr operator  ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*() noexcept;

/// @brief Method ABlRPBvRzZmfslupWjSWCJkYRdVF, addr 0x180c29b80, size 0x2090, virtual false, abstract: false, final false
inline void ABlRPBvRzZmfslupWjSWCJkYRdVF(bool  _cordl_fixed_empty_name_whitespace) ;

static inline ::Rewired::InputCategory* New_ctor() ;

static inline ::Rewired::InputCategory* New_ctor(::Rewired::InputCategory*  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method RWcOabOsZPKPgubAWAQqbVGNpCcUA, addr 0x1819a52f0, size 0x30, virtual true, abstract: false, final false
inline void RWcOabOsZPKPgubAWAQqbVGNpCcUA() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_autoGeneratedValueFlags, addr 0x1803eb0e0, size 0x10, virtual true, abstract: false, final true
inline int32_t Rewired_Internal_Localization_INameLocalizerSource_get_autoGeneratedValueFlags() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_key, addr 0x1802d97e0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_key() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_keyCategory, addr 0x180303b80, size 0x20, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_keyCategory() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_nonLocalizedDescriptiveName, addr 0x1802ecc10, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_nonLocalizedDescriptiveName() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_scriptingName, addr 0x1802db4a0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_scriptingName() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.set_autoGeneratedValueFlags, addr 0x180511530, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_INameLocalizerSource_set_autoGeneratedValueFlags(int32_t  value) ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.set_nonLocalizedDescriptiveName, addr 0x1802ecc20, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_INameLocalizerSource_set_nonLocalizedDescriptiveName(::StringW  value) ;

/// @brief Method UmikgmkPBmgwTCOmEOxqIKoIMcmqA, addr 0x180308500, size 0x30, virtual false, abstract: false, final false
inline void UmikgmkPBmgwTCOmEOxqIKoIMcmqA(::StringW  _cordl_fixed_empty_name_whitespace) ;

constexpr ::StringW const& __cordl_internal_get__descriptiveName() const;

constexpr ::StringW& __cordl_internal_get__descriptiveName() ;

constexpr int32_t const& __cordl_internal_get__id() const;

constexpr int32_t& __cordl_internal_get__id() ;

constexpr ::StringW const& __cordl_internal_get__key() const;

constexpr ::StringW& __cordl_internal_get__key() ;

constexpr ::StringW const& __cordl_internal_get__name() const;

constexpr ::StringW& __cordl_internal_get__name() ;

constexpr ::StringW const& __cordl_internal_get__tag() const;

constexpr ::StringW& __cordl_internal_get__tag() ;

constexpr bool const& __cordl_internal_get__userAssignable() const;

constexpr bool& __cordl_internal_get__userAssignable() ;

constexpr int32_t const& __cordl_internal_get_eunPorGirRtQCNqohfdyruBJnrTm() const;

constexpr int32_t& __cordl_internal_get_eunPorGirRtQCNqohfdyruBJnrTm() ;

constexpr ::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ* const& __cordl_internal_get_iTSyCBIXSpclRYBgrRqzlsERkHmP() const;

constexpr ::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ*& __cordl_internal_get_iTSyCBIXSpclRYBgrRqzlsERkHmP() ;

constexpr void __cordl_internal_set__descriptiveName(::StringW  value) ;

constexpr void __cordl_internal_set__id(int32_t  value) ;

constexpr void __cordl_internal_set__key(::StringW  value) ;

constexpr void __cordl_internal_set__name(::StringW  value) ;

constexpr void __cordl_internal_set__tag(::StringW  value) ;

constexpr void __cordl_internal_set__userAssignable(bool  value) ;

constexpr void __cordl_internal_set_eunPorGirRtQCNqohfdyruBJnrTm(int32_t  value) ;

constexpr void __cordl_internal_set_iTSyCBIXSpclRYBgrRqzlsERkHmP(::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ*  value) ;

/// @brief Method .ctor, addr 0x1802d9d80, size 0x10, virtual false, abstract: false, final false
inline void _ctor() ;

/// @brief Method .ctor, addr 0x1819a3420, size 0x80, virtual false, abstract: false, final false
inline void _ctor(::Rewired::InputCategory*  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method dCjnJOIdlsmskHqZRhLbeUuQRzbo, addr 0x1819a5320, size 0x90, virtual false, abstract: false, final false
inline void dCjnJOIdlsmskHqZRhLbeUuQRzbo(::StringW  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method euDEcCRNCLyCyycWzhuPUCzRohwN, addr 0x1802e2f70, size 0x10, virtual false, abstract: false, final false
inline void euDEcCRNCLyCyycWzhuPUCzRohwN(int32_t  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method get_descriptiveName, addr 0x1819a53b0, size 0x90, virtual false, abstract: false, final false
inline ::StringW get_descriptiveName() ;

/// @brief Method get_id, addr 0x1802e2ba0, size 0x10, virtual false, abstract: false, final false
inline int32_t get_id() ;

/// @brief Method get_key, addr 0x1802d97e0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_key() ;

/// @brief Method get_keyCategory, addr 0xffffffffffffffff, size 0xffffffffffffffff, virtual true, abstract: false, final false
inline ::StringW get_keyCategory() ;

/// @brief Method get_name, addr 0x1802db4a0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_name() ;

/// @brief Method get_nonLocalizedDescriptiveName, addr 0x1802ecc10, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_nonLocalizedDescriptiveName() ;

/// @brief Method get_tag, addr 0x1802d9810, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_tag() ;

/// @brief Method get_userAssignable, addr 0x1803e0b00, size 0x10, virtual false, abstract: false, final false
inline bool get_userAssignable() ;

/// @brief Convert to "::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA"
constexpr ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA* i___GlobalNamespace__ilReClayUpFdClpKxnBeDJuNJPBMA() noexcept;

/// @brief Method pKTKDSlAFxfFpEesqQjurTTiupBqA, addr 0x1802d9d80, size 0x10, virtual true, abstract: false, final false
inline void pKTKDSlAFxfFpEesqQjurTTiupBqA() ;

/// @brief Method set_key, addr 0x1819a5440, size 0x90, virtual false, abstract: false, final false
inline void set_key(::StringW  value) ;

/// @brief Method set_nonLocalizedDescriptiveName, addr 0x1819a5320, size 0x90, virtual false, abstract: false, final false
inline void set_nonLocalizedDescriptiveName(::StringW  value) ;

/// @brief Method wlUujZefviMZbATAxmxOSvHqFhaO, addr 0x1802d9850, size 0x10, virtual false, abstract: false, final false
inline void wlUujZefviMZbATAxmxOSvHqFhaO(::StringW  _cordl_fixed_empty_name_whitespace) ;

protected:
// Ctor Parameters []
// @brief default ctor
constexpr InputCategory() ;
public:

// Ctor Parameters [CppParam { name: "", ty: "InputCategory", modifiers: "&&", def_value: None }]
// @brief delete move ctor to prevent accidental deref moves
InputCategory(InputCategory && ) = delete;

// Ctor Parameters [CppParam { name: "", ty: "InputCategory", modifiers: "const&", def_value: None }]
// @brief delete copy ctor to prevent accidental deref copies
InputCategory(InputCategory const& ) = delete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{2076};

/// @brief Field _name, offset: 0x10, size: 0x8, def value: None
 ::StringW  ____name;

/// @brief Field _descriptiveName, offset: 0x18, size: 0x8, def value: None
 ::StringW  ____descriptiveName;

/// @brief Field _key, offset: 0x20, size: 0x8, def value: None
 ::StringW  ____key;

/// @brief Field _tag, offset: 0x28, size: 0x8, def value: None
 ::StringW  ____tag;

/// @brief Field _id, offset: 0x30, size: 0x4, def value: None
 int32_t  ____id;

/// @brief Field _userAssignable, offset: 0x34, size: 0x1, def value: None
 bool  ____userAssignable;

/// @brief Field iTSyCBIXSpclRYBgrRqzlsERkHmP, offset: 0x38, size: 0x8, def value: None
 ::GlobalNamespace::vKlxFVEhQCQotaZlQCGnJzUBdQtQ*  ___iTSyCBIXSpclRYBgrRqzlsERkHmP;

/// @brief Field eunPorGirRtQCNqohfdyruBJnrTm, offset: 0x40, size: 0x4, def value: None
 int32_t  ___eunPorGirRtQCNqohfdyruBJnrTm;

static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
static_assert(offsetof(::Rewired::InputCategory, ____name) == 0x10, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputCategory, ____descriptiveName) == 0x18, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputCategory, ____key) == 0x20, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputCategory, ____tag) == 0x28, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputCategory, ____id) == 0x30, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputCategory, ____userAssignable) == 0x34, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputCategory, ___iTSyCBIXSpclRYBgrRqzlsERkHmP) == 0x38, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputCategory, ___eunPorGirRtQCNqohfdyruBJnrTm) == 0x40, "Offset mismatch!");

static_assert(sizeof(::Rewired::InputCategory) == 0x48, "Size mismatch!");

} // namespace end def Rewired
