#pragma once
// IWYU pragma private; include "Rewired/InputAction.hpp"
#include "beatsaber-hook/shared/types.hpp"
#include "../cordl_internals/cordl_internals.hpp"
CORDL_MODULE_INIT
#include "Rewired/zzzz__InputActionType_def.hpp"
#include "System/zzzz__Object_def.hpp"
#include "beatsaber-hook/shared/stringw.hpp"
#include <cstdint>
CORDL_MODULE_EXPORT(InputAction)
namespace GlobalNamespace {
struct KlcNeaFZiwoAzlYmohbMFFSmhxYd_lyYnxgykwvOmykWBuGmMtGqjBdhI;
}
namespace GlobalNamespace {
class aaIrhkVuamEdkpKYgMrcawdVREgJ;
}
namespace GlobalNamespace {
class ilReClayUpFdClpKxnBeDJuNJPBMA;
}
namespace GlobalNamespace {
class uPqZXSqQQWpZJAQVQzbvGgYSEAkO;
}
namespace Rewired {
struct AxisRange;
}
namespace Rewired {
struct InputActionType;
}
// Forward declare root types
namespace Rewired {
class InputAction;
}
// Write type traits
MARK_REF_T(::Rewired::InputAction*);
DEFINE_IL2CPP_CLASS(::Rewired::InputAction*, "Rewired", "InputAction");
// Dependencies Rewired.InputActionType, System.Object
namespace Rewired {
// Is value type: false
// CS Name: Rewired.InputAction
class CORDL_TYPE InputAction : public ::System::Object {
public:
// Declarations
/// @brief Field IjaboSewgnbprHqUIlOEecJOyxbp, offset 0x68, size 0x8 
 __declspec(property(get=__cordl_internal_get_IjaboSewgnbprHqUIlOEecJOyxbp, put=__cordl_internal_set_IjaboSewgnbprHqUIlOEecJOyxbp)) ::GlobalNamespace::uPqZXSqQQWpZJAQVQzbvGgYSEAkO*  IjaboSewgnbprHqUIlOEecJOyxbp;

 __declspec(property(get=Rewired_Internal_Localization_IAxisNameLocalizerSource_get_negativeKey, put=Rewired_Internal_Localization_IAxisNameLocalizerSource_set_negativeKey)) ::StringW  Rewired_Internal_Localization_IAxisNameLocalizerSource_negativeKey;

 __declspec(property(get=Rewired_Internal_Localization_IAxisNameLocalizerSource_get_nonLocalizedNegativeDescriptiveName, put=Rewired_Internal_Localization_IAxisNameLocalizerSource_set_nonLocalizedNegativeDescriptiveName)) ::StringW  Rewired_Internal_Localization_IAxisNameLocalizerSource_nonLocalizedNegativeDescriptiveName;

 __declspec(property(get=Rewired_Internal_Localization_IAxisNameLocalizerSource_get_nonLocalizedPositiveDescriptiveName, put=Rewired_Internal_Localization_IAxisNameLocalizerSource_set_nonLocalizedPositiveDescriptiveName)) ::StringW  Rewired_Internal_Localization_IAxisNameLocalizerSource_nonLocalizedPositiveDescriptiveName;

 __declspec(property(get=Rewired_Internal_Localization_IAxisNameLocalizerSource_get_positiveKey, put=Rewired_Internal_Localization_IAxisNameLocalizerSource_set_positiveKey)) ::StringW  Rewired_Internal_Localization_IAxisNameLocalizerSource_positiveKey;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_autoGeneratedValueFlags, put=Rewired_Internal_Localization_INameLocalizerSource_set_autoGeneratedValueFlags)) int32_t  Rewired_Internal_Localization_INameLocalizerSource_autoGeneratedValueFlags;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_key)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_key;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_keyCategory)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_keyCategory;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_nonLocalizedDescriptiveName, put=Rewired_Internal_Localization_INameLocalizerSource_set_nonLocalizedDescriptiveName)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_nonLocalizedDescriptiveName;

 __declspec(property(get=Rewired_Internal_Localization_INameLocalizerSource_get_scriptingName)) ::StringW  Rewired_Internal_Localization_INameLocalizerSource_scriptingName;

/// @brief Field THdwGWiDpTXhApasowlcBKfNHmec, offset 0x70, size 0x4 
 __declspec(property(get=__cordl_internal_get_THdwGWiDpTXhApasowlcBKfNHmec, put=__cordl_internal_set_THdwGWiDpTXhApasowlcBKfNHmec)) int32_t  THdwGWiDpTXhApasowlcBKfNHmec;

/// @brief Field _behaviorId, offset 0x58, size 0x4 
 __declspec(property(get=__cordl_internal_get__behaviorId, put=__cordl_internal_set__behaviorId)) int32_t  _behaviorId;

/// @brief Field _categoryId, offset 0x60, size 0x4 
 __declspec(property(get=__cordl_internal_get__categoryId, put=__cordl_internal_set__categoryId)) int32_t  _categoryId;

/// @brief Field _descriptiveName, offset 0x28, size 0x8 
 __declspec(property(get=__cordl_internal_get__descriptiveName, put=__cordl_internal_set__descriptiveName)) ::StringW  _descriptiveName;

/// @brief Field _id, offset 0x10, size 0x4 
 __declspec(property(get=__cordl_internal_get__id, put=__cordl_internal_set__id)) int32_t  _id;

/// @brief Field _key, offset 0x40, size 0x8 
 __declspec(property(get=__cordl_internal_get__key, put=__cordl_internal_set__key)) ::StringW  _key;

/// @brief Field _name, offset 0x18, size 0x8 
 __declspec(property(get=__cordl_internal_get__name, put=__cordl_internal_set__name)) ::StringW  _name;

/// @brief Field _negativeDescriptiveName, offset 0x38, size 0x8 
 __declspec(property(get=__cordl_internal_get__negativeDescriptiveName, put=__cordl_internal_set__negativeDescriptiveName)) ::StringW  _negativeDescriptiveName;

/// @brief Field _negativeKey, offset 0x50, size 0x8 
 __declspec(property(get=__cordl_internal_get__negativeKey, put=__cordl_internal_set__negativeKey)) ::StringW  _negativeKey;

/// @brief Field _positiveDescriptiveName, offset 0x30, size 0x8 
 __declspec(property(get=__cordl_internal_get__positiveDescriptiveName, put=__cordl_internal_set__positiveDescriptiveName)) ::StringW  _positiveDescriptiveName;

/// @brief Field _positiveKey, offset 0x48, size 0x8 
 __declspec(property(get=__cordl_internal_get__positiveKey, put=__cordl_internal_set__positiveKey)) ::StringW  _positiveKey;

/// @brief Field _type, offset 0x20, size 0x4 
 __declspec(property(get=__cordl_internal_get__type, put=__cordl_internal_set__type)) ::Rewired::InputActionType  _type;

/// @brief Field _userAssignable, offset 0x5c, size 0x1 
 __declspec(property(get=__cordl_internal_get__userAssignable, put=__cordl_internal_set__userAssignable)) bool  _userAssignable;

 __declspec(property(get=get_behaviorId, put=uyniHBfCUEgyPbPdjBpWzfLQFGJX)) int32_t  behaviorId;

 __declspec(property(get=get_categoryId, put=WMSbvzDkjEaOVgesPUQpWcyvoNOr)) int32_t  categoryId;

 __declspec(property(get=get_descriptiveName, put=EkDjGNcrYQKhVoGrFPnSWOadGldd)) ::StringW  descriptiveName;

 __declspec(property(get=get_id, put=pOtqCNizKWRPwFNoRHWYwwhWLbZW)) int32_t  id;

 __declspec(property(get=get_key, put=set_key)) ::StringW  key;

 __declspec(property(get=get_name, put=zYqJRrpMlnTpLbZHaDSLnKqxaVXn)) ::StringW  name;

 __declspec(property(get=get_negativeDescriptiveName, put=RjbjonOHRxQYLQnSDGnuCHhFnNtX)) ::StringW  negativeDescriptiveName;

 __declspec(property(get=get_negativeKey, put=set_negativeKey)) ::StringW  negativeKey;

 __declspec(property(get=get_nonLocalizedDescriptiveName, put=set_nonLocalizedDescriptiveName)) ::StringW  nonLocalizedDescriptiveName;

 __declspec(property(get=get_nonLocalizedNegativeDescriptiveName, put=set_nonLocalizedNegativeDescriptiveName)) ::StringW  nonLocalizedNegativeDescriptiveName;

 __declspec(property(get=get_nonLocalizedPositiveDescriptiveName, put=set_nonLocalizedPositiveDescriptiveName)) ::StringW  nonLocalizedPositiveDescriptiveName;

 __declspec(property(get=get_positiveDescriptiveName, put=BdWbYDfcnOlHHCeHYpVfUhufcmOVA)) ::StringW  positiveDescriptiveName;

 __declspec(property(get=get_positiveKey, put=set_positiveKey)) ::StringW  positiveKey;

 __declspec(property(get=get_type, put=xdRFBvgdTzeOwUIOzFEYsDPKvaNBA)) ::Rewired::InputActionType  type;

 __declspec(property(get=get_userAssignable, put=wVmgMgCQtOXFbODeVlmGSYjacGpaA)) bool  userAssignable;

/// @brief Convert operator to "::GlobalNamespace::aaIrhkVuamEdkpKYgMrcawdVREgJ"
constexpr operator  ::GlobalNamespace::aaIrhkVuamEdkpKYgMrcawdVREgJ*() noexcept;

/// @brief Convert operator to "::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA"
constexpr operator  ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA*() noexcept;

/// @brief Method BdWbYDfcnOlHHCeHYpVfUhufcmOVA, addr 0x1819a34b0, size 0x80, virtual false, abstract: false, final false
inline void BdWbYDfcnOlHHCeHYpVfUhufcmOVA(::StringW  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method Clone, addr 0x1819a3530, size 0xe0, virtual false, abstract: false, final false
inline ::Rewired::InputAction* Clone() ;

/// @brief Method EkDjGNcrYQKhVoGrFPnSWOadGldd, addr 0x1819a3610, size 0x90, virtual false, abstract: false, final false
inline void EkDjGNcrYQKhVoGrFPnSWOadGldd(::StringW  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method GetDisplayName, addr 0x1819a36a0, size 0x1b0, virtual false, abstract: false, final false
inline ::StringW GetDisplayName(::Rewired::AxisRange  axisRange) ;

static inline ::Rewired::InputAction* New_ctor() ;

static inline ::Rewired::InputAction* New_ctor(::Rewired::InputAction*  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method RbThQZHRgVIAJXkexEdxVVwZyUniA, addr 0x1819a3850, size 0x60, virtual false, abstract: false, final false
inline void RbThQZHRgVIAJXkexEdxVVwZyUniA() ;

/// @brief Method Rewired.Internal.Localization.IAxisNameLocalizerSource.get_negativeKey, addr 0x1802e0b30, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_IAxisNameLocalizerSource_get_negativeKey() ;

/// @brief Method Rewired.Internal.Localization.IAxisNameLocalizerSource.get_nonLocalizedNegativeDescriptiveName, addr 0x1802d9800, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_IAxisNameLocalizerSource_get_nonLocalizedNegativeDescriptiveName() ;

/// @brief Method Rewired.Internal.Localization.IAxisNameLocalizerSource.get_nonLocalizedPositiveDescriptiveName, addr 0x1802d97f0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_IAxisNameLocalizerSource_get_nonLocalizedPositiveDescriptiveName() ;

/// @brief Method Rewired.Internal.Localization.IAxisNameLocalizerSource.get_positiveKey, addr 0x1802e58c0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_IAxisNameLocalizerSource_get_positiveKey() ;

/// @brief Method Rewired.Internal.Localization.IAxisNameLocalizerSource.set_negativeKey, addr 0x180308de0, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_IAxisNameLocalizerSource_set_negativeKey(::StringW  value) ;

/// @brief Method Rewired.Internal.Localization.IAxisNameLocalizerSource.set_nonLocalizedNegativeDescriptiveName, addr 0x1802d9840, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_IAxisNameLocalizerSource_set_nonLocalizedNegativeDescriptiveName(::StringW  value) ;

/// @brief Method Rewired.Internal.Localization.IAxisNameLocalizerSource.set_nonLocalizedPositiveDescriptiveName, addr 0x1802d9830, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_IAxisNameLocalizerSource_set_nonLocalizedPositiveDescriptiveName(::StringW  value) ;

/// @brief Method Rewired.Internal.Localization.IAxisNameLocalizerSource.set_positiveKey, addr 0x1802e5e30, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_IAxisNameLocalizerSource_set_positiveKey(::StringW  value) ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_autoGeneratedValueFlags, addr 0x1803fa740, size 0x10, virtual true, abstract: false, final true
inline int32_t Rewired_Internal_Localization_INameLocalizerSource_get_autoGeneratedValueFlags() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_key, addr 0x1802e5850, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_key() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_keyCategory, addr 0x1819a38b0, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_keyCategory() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_nonLocalizedDescriptiveName, addr 0x1802d9810, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_nonLocalizedDescriptiveName() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.get_scriptingName, addr 0x1802ecc10, size 0x10, virtual true, abstract: false, final true
inline ::StringW Rewired_Internal_Localization_INameLocalizerSource_get_scriptingName() ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.set_autoGeneratedValueFlags, addr 0x18051e950, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_INameLocalizerSource_set_autoGeneratedValueFlags(int32_t  value) ;

/// @brief Method Rewired.Internal.Localization.INameLocalizerSource.set_nonLocalizedDescriptiveName, addr 0x1802d9850, size 0x10, virtual true, abstract: false, final true
inline void Rewired_Internal_Localization_INameLocalizerSource_set_nonLocalizedDescriptiveName(::StringW  value) ;

/// @brief Method RjbjonOHRxQYLQnSDGnuCHhFnNtX, addr 0x1819a38c0, size 0x80, virtual false, abstract: false, final false
inline void RjbjonOHRxQYLQnSDGnuCHhFnNtX(::StringW  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method WMSbvzDkjEaOVgesPUQpWcyvoNOr, addr 0x1804f67b0, size 0x10, virtual false, abstract: false, final false
inline void WMSbvzDkjEaOVgesPUQpWcyvoNOr(int32_t  _cordl_fixed_empty_name_whitespace) ;

constexpr ::GlobalNamespace::uPqZXSqQQWpZJAQVQzbvGgYSEAkO* const& __cordl_internal_get_IjaboSewgnbprHqUIlOEecJOyxbp() const;

constexpr ::GlobalNamespace::uPqZXSqQQWpZJAQVQzbvGgYSEAkO*& __cordl_internal_get_IjaboSewgnbprHqUIlOEecJOyxbp() ;

constexpr int32_t const& __cordl_internal_get_THdwGWiDpTXhApasowlcBKfNHmec() const;

constexpr int32_t& __cordl_internal_get_THdwGWiDpTXhApasowlcBKfNHmec() ;

constexpr int32_t const& __cordl_internal_get__behaviorId() const;

constexpr int32_t& __cordl_internal_get__behaviorId() ;

constexpr int32_t const& __cordl_internal_get__categoryId() const;

constexpr int32_t& __cordl_internal_get__categoryId() ;

constexpr ::StringW const& __cordl_internal_get__descriptiveName() const;

constexpr ::StringW& __cordl_internal_get__descriptiveName() ;

constexpr int32_t const& __cordl_internal_get__id() const;

constexpr int32_t& __cordl_internal_get__id() ;

constexpr ::StringW const& __cordl_internal_get__key() const;

constexpr ::StringW& __cordl_internal_get__key() ;

constexpr ::StringW const& __cordl_internal_get__name() const;

constexpr ::StringW& __cordl_internal_get__name() ;

constexpr ::StringW const& __cordl_internal_get__negativeDescriptiveName() const;

constexpr ::StringW& __cordl_internal_get__negativeDescriptiveName() ;

constexpr ::StringW const& __cordl_internal_get__negativeKey() const;

constexpr ::StringW& __cordl_internal_get__negativeKey() ;

constexpr ::StringW const& __cordl_internal_get__positiveDescriptiveName() const;

constexpr ::StringW& __cordl_internal_get__positiveDescriptiveName() ;

constexpr ::StringW const& __cordl_internal_get__positiveKey() const;

constexpr ::StringW& __cordl_internal_get__positiveKey() ;

constexpr ::Rewired::InputActionType const& __cordl_internal_get__type() const;

constexpr ::Rewired::InputActionType& __cordl_internal_get__type() ;

constexpr bool const& __cordl_internal_get__userAssignable() const;

constexpr bool& __cordl_internal_get__userAssignable() ;

constexpr void __cordl_internal_set_IjaboSewgnbprHqUIlOEecJOyxbp(::GlobalNamespace::uPqZXSqQQWpZJAQVQzbvGgYSEAkO*  value) ;

constexpr void __cordl_internal_set_THdwGWiDpTXhApasowlcBKfNHmec(int32_t  value) ;

constexpr void __cordl_internal_set__behaviorId(int32_t  value) ;

constexpr void __cordl_internal_set__categoryId(int32_t  value) ;

constexpr void __cordl_internal_set__descriptiveName(::StringW  value) ;

constexpr void __cordl_internal_set__id(int32_t  value) ;

constexpr void __cordl_internal_set__key(::StringW  value) ;

constexpr void __cordl_internal_set__name(::StringW  value) ;

constexpr void __cordl_internal_set__negativeDescriptiveName(::StringW  value) ;

constexpr void __cordl_internal_set__negativeKey(::StringW  value) ;

constexpr void __cordl_internal_set__positiveDescriptiveName(::StringW  value) ;

constexpr void __cordl_internal_set__positiveKey(::StringW  value) ;

constexpr void __cordl_internal_set__type(::Rewired::InputActionType  value) ;

constexpr void __cordl_internal_set__userAssignable(bool  value) ;

/// @brief Method .ctor, addr 0x1802d9d80, size 0x10, virtual false, abstract: false, final false
inline void _ctor() ;

/// @brief Method .ctor, addr 0x1819a3940, size 0xd0, virtual false, abstract: false, final false
inline void _ctor(::Rewired::InputAction*  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method cEzfqinrzjUISjiCcLlHTHPCSygK, addr 0x1819a3a10, size 0x20, virtual false, abstract: false, final false
inline void cEzfqinrzjUISjiCcLlHTHPCSygK() ;

/// @brief Method get_behaviorId, addr 0x1802e0b20, size 0x10, virtual false, abstract: false, final false
inline int32_t get_behaviorId() ;

/// @brief Method get_categoryId, addr 0x18039fc60, size 0x10, virtual false, abstract: false, final false
inline int32_t get_categoryId() ;

/// @brief Method get_descriptiveName, addr 0x1819a3a30, size 0x90, virtual false, abstract: false, final false
inline ::StringW get_descriptiveName() ;

/// @brief Method get_id, addr 0x180303b50, size 0x10, virtual false, abstract: false, final false
inline int32_t get_id() ;

/// @brief Method get_key, addr 0x1802e5850, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_key() ;

/// @brief Method get_name, addr 0x1802ecc10, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_name() ;

/// @brief Method get_negativeDescriptiveName, addr 0x1819a3ac0, size 0x90, virtual false, abstract: false, final false
inline ::StringW get_negativeDescriptiveName() ;

/// @brief Method get_negativeKey, addr 0x1802e0b30, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_negativeKey() ;

/// @brief Method get_nonLocalizedDescriptiveName, addr 0x1802d9810, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_nonLocalizedDescriptiveName() ;

/// @brief Method get_nonLocalizedNegativeDescriptiveName, addr 0x1802d9800, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_nonLocalizedNegativeDescriptiveName() ;

/// @brief Method get_nonLocalizedPositiveDescriptiveName, addr 0x1802d97f0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_nonLocalizedPositiveDescriptiveName() ;

/// @brief Method get_positiveDescriptiveName, addr 0x1819a3b50, size 0x90, virtual false, abstract: false, final false
inline ::StringW get_positiveDescriptiveName() ;

/// @brief Method get_positiveKey, addr 0x1802e58c0, size 0x10, virtual false, abstract: false, final false
inline ::StringW get_positiveKey() ;

/// @brief Method get_type, addr 0x180396ee0, size 0x10, virtual false, abstract: false, final false
inline ::Rewired::InputActionType get_type() ;

/// @brief Method get_userAssignable, addr 0x1802e09d0, size 0x10, virtual false, abstract: false, final false
inline bool get_userAssignable() ;

/// @brief Convert to "::GlobalNamespace::aaIrhkVuamEdkpKYgMrcawdVREgJ"
constexpr ::GlobalNamespace::aaIrhkVuamEdkpKYgMrcawdVREgJ* i___GlobalNamespace__aaIrhkVuamEdkpKYgMrcawdVREgJ() noexcept;

/// @brief Convert to "::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA"
constexpr ::GlobalNamespace::ilReClayUpFdClpKxnBeDJuNJPBMA* i___GlobalNamespace__ilReClayUpFdClpKxnBeDJuNJPBMA() noexcept;

/// @brief Method pOtqCNizKWRPwFNoRHWYwwhWLbZW, addr 0x180378ff0, size 0x10, virtual false, abstract: false, final false
inline void pOtqCNizKWRPwFNoRHWYwwhWLbZW(int32_t  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method set_key, addr 0x1819a3be0, size 0x90, virtual false, abstract: false, final false
inline void set_key(::StringW  value) ;

/// @brief Method set_negativeKey, addr 0x1819a3c70, size 0x80, virtual false, abstract: false, final false
inline void set_negativeKey(::StringW  value) ;

/// @brief Method set_nonLocalizedDescriptiveName, addr 0x1819a3610, size 0x90, virtual false, abstract: false, final false
inline void set_nonLocalizedDescriptiveName(::StringW  value) ;

/// @brief Method set_nonLocalizedNegativeDescriptiveName, addr 0x1819a38c0, size 0x80, virtual false, abstract: false, final false
inline void set_nonLocalizedNegativeDescriptiveName(::StringW  value) ;

/// @brief Method set_nonLocalizedPositiveDescriptiveName, addr 0x1819a34b0, size 0x80, virtual false, abstract: false, final false
inline void set_nonLocalizedPositiveDescriptiveName(::StringW  value) ;

/// @brief Method set_positiveKey, addr 0x1819a3cf0, size 0x80, virtual false, abstract: false, final false
inline void set_positiveKey(::StringW  value) ;

/// @brief Method uyniHBfCUEgyPbPdjBpWzfLQFGJX, addr 0x1802e0d10, size 0x10, virtual false, abstract: false, final false
inline void uyniHBfCUEgyPbPdjBpWzfLQFGJX(int32_t  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method wVmgMgCQtOXFbODeVlmGSYjacGpaA, addr 0x18051e980, size 0x10, virtual false, abstract: false, final false
inline void wVmgMgCQtOXFbODeVlmGSYjacGpaA(bool  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method xdRFBvgdTzeOwUIOzFEYsDPKvaNBA, addr 0x1819a3d70, size 0xa0, virtual false, abstract: false, final false
inline void xdRFBvgdTzeOwUIOzFEYsDPKvaNBA(::Rewired::InputActionType  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method zYqJRrpMlnTpLbZHaDSLnKqxaVXn, addr 0x1819a3e10, size 0x90, virtual false, abstract: false, final false
inline void zYqJRrpMlnTpLbZHaDSLnKqxaVXn(::StringW  _cordl_fixed_empty_name_whitespace) ;

/// @brief Method zaLOrauUSaBHHnPnNIuvyPQuELkl, addr 0x1818430e0, size 0x30, virtual false, abstract: false, final false
static inline ::GlobalNamespace::KlcNeaFZiwoAzlYmohbMFFSmhxYd_lyYnxgykwvOmykWBuGmMtGqjBdhI zaLOrauUSaBHHnPnNIuvyPQuELkl(::Rewired::InputActionType  _cordl_fixed_empty_name_whitespace) ;

protected:
// Ctor Parameters []
// @brief default ctor
constexpr InputAction() ;
public:

// Ctor Parameters [CppParam { name: "", ty: "InputAction", modifiers: "&&", def_value: None }]
// @brief delete move ctor to prevent accidental deref moves
InputAction(InputAction && ) = delete;

// Ctor Parameters [CppParam { name: "", ty: "InputAction", modifiers: "const&", def_value: None }]
// @brief delete copy ctor to prevent accidental deref copies
InputAction(InputAction const& ) = delete;

/// @brief IL2CPP Metadata Type Index
static constexpr uint32_t  __IL2CPP_TYPE_DEFINITION_INDEX{2074};

/// @brief Field keyCategory offset 0xffffffff size 0x8
static constexpr ::ConstString  keyCategory{u"action"};

/// @brief Field _id, offset: 0x10, size: 0x4, def value: None
 int32_t  ____id;

/// @brief Field _name, offset: 0x18, size: 0x8, def value: None
 ::StringW  ____name;

/// @brief Field _type, offset: 0x20, size: 0x4, def value: None
 ::Rewired::InputActionType  ____type;

/// @brief Field _descriptiveName, offset: 0x28, size: 0x8, def value: None
 ::StringW  ____descriptiveName;

/// @brief Field _positiveDescriptiveName, offset: 0x30, size: 0x8, def value: None
 ::StringW  ____positiveDescriptiveName;

/// @brief Field _negativeDescriptiveName, offset: 0x38, size: 0x8, def value: None
 ::StringW  ____negativeDescriptiveName;

/// @brief Field _key, offset: 0x40, size: 0x8, def value: None
 ::StringW  ____key;

/// @brief Field _positiveKey, offset: 0x48, size: 0x8, def value: None
 ::StringW  ____positiveKey;

/// @brief Field _negativeKey, offset: 0x50, size: 0x8, def value: None
 ::StringW  ____negativeKey;

/// @brief Field _behaviorId, offset: 0x58, size: 0x4, def value: None
 int32_t  ____behaviorId;

/// @brief Field _userAssignable, offset: 0x5c, size: 0x1, def value: None
 bool  ____userAssignable;

/// @brief Field _categoryId, offset: 0x60, size: 0x4, def value: None
 int32_t  ____categoryId;

/// @brief Field IjaboSewgnbprHqUIlOEecJOyxbp, offset: 0x68, size: 0x8, def value: None
 ::GlobalNamespace::uPqZXSqQQWpZJAQVQzbvGgYSEAkO*  ___IjaboSewgnbprHqUIlOEecJOyxbp;

/// @brief Field THdwGWiDpTXhApasowlcBKfNHmec, offset: 0x70, size: 0x4, def value: None
 int32_t  ___THdwGWiDpTXhApasowlcBKfNHmec;

static constexpr bool __IL2CPP_IS_VALUE_TYPE = false;
};
// Non member Declarations
static_assert(offsetof(::Rewired::InputAction, ____id) == 0x10, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____name) == 0x18, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____type) == 0x20, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____descriptiveName) == 0x28, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____positiveDescriptiveName) == 0x30, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____negativeDescriptiveName) == 0x38, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____key) == 0x40, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____positiveKey) == 0x48, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____negativeKey) == 0x50, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____behaviorId) == 0x58, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____userAssignable) == 0x5c, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ____categoryId) == 0x60, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ___IjaboSewgnbprHqUIlOEecJOyxbp) == 0x68, "Offset mismatch!");

static_assert(offsetof(::Rewired::InputAction, ___THdwGWiDpTXhApasowlcBKfNHmec) == 0x70, "Offset mismatch!");

static_assert(sizeof(::Rewired::InputAction) == 0x78, "Size mismatch!");

} // namespace end def Rewired
